export const soalData = [
  { nomor: 1, soal: "Siapakah nama raja pertama bangsa Israel?", jawaban: "Saul (1Samuel 9)" },
  { nomor: 2, soal: "Siapakah nama raja yang terkenal dengan hikmat dan kebijaksanaannya?", jawaban: "Salomo (1raja-raja 3)" },
  { nomor: 3, soal: "Siapakah nama raja Moab yang disebutkan sangat gendut?", jawaban: "Eglon (hakim-hakim 3:17)" },
  { nomor: 4, soal: "Siapakah raja yang bunuh diri dengan membakar istananya sendiri?", jawaban: "Zimri (1raja-raja 16:18)" },
  { nomor: 5, soal: "Siapakah raja yang naik tahta dengan umur termuda?", jawaban: "Yoas (2raja-raja 11:21)" },
  { nomor: 6, soal: "Siapakah raja Asyur yang dibunuh oleh anak-anaknya di kuil?", jawaban: "Sanherib (2raja-raja 19:37)" },
  { nomor: 7, soal: "Siapakah nama cucu dari Raja Saul,yang kakinya timpang?", jawaban: "Mefiboset (2Samuel 9)" },
  { nomor: 8, soal: "Siapakah nama ayah dari Raja Saul?", jawaban: "Kish (1Samuel 9)" },
  { nomor: 9, soal: "Siapakah nama hakim pertama bangsa israel?", jawaban: "Otniel (hakim-hakim 3:7-11)" },
  { nomor: 10, soal: "Siapakah nama hakim yang bertangan kidal?", jawaban: "Ehud (hakim-hakim 3:15)" },
  { nomor: 11, soal: "Siapakah nama nabi yang memakan gulungan kitab,yang di mulutnya berasa manis seperti madu tetapi kemudian di perutnya terasa pahit?", jawaban: "Yohanes (Wahyu 10:10)" },
  { nomor: 12, soal: "Siapakah nama nabiah yang terkena kusta?", jawaban: "Miryam (keluaran 15:20,Bilangan 12:10)" },
  { nomor: 13, soal: "Siapakah nabi yang menikahi perempuan sundal?", jawaban: "Hosea (Hosea 1:2-3)" },
  { nomor: 14, soal: "Siapakah nama nabi yang memperingatkan Daud tentang dosa perzinahannya?", jawaban: "Natan (2Samuel 12)" },
  { nomor: 15, soal: "Siapakah nama nabi yang pekerjaannya sebagai peternak dan pemungut buah ara?", jawaban: "Amos (Amos 1)" },
  { nomor: 16, soal: "Siapakah nabi yang berjalan telanjang dan tak berkasut 3tahun lamanya?", jawaban: "Yesaya (yesaya 20:2-3)" },
  { nomor: 17, soal: "Siapakah nama bujang dari nabi Elisa?", jawaban: "Gehazi (2raja-raja 4:12)" },
  { nomor: 18, soal: "Saat Paulus dan Barnabas berselisih mereka berpisah,Paulus memilih membawa Silas sedangkan Barnabas memilih membawa siapa?", jawaban: "Yohanes yang disebut Markus (Kis 15:39)" },
  { nomor: 19, soal: "Siapakah nama wanita yang dibangkitkan oleh Petrus?", jawaban: "Dorkas (Kis 9:36-43)" },
  { nomor: 20, soal: "Siapakah nama orang yang jatuh dari jendela saat Paulus berkotbah?", jawaban: "Eutikhus (Kis 20:29)" },
  { nomor: 21, soal: "Siapakah nama ayah dari murid Yesus yang disebut Boarnerges?", jawaban: "Zebedeus (Markus 3:17)" },
  { nomor: 22, soal: "Berapa banyak ikan besar yang berhasil ditangkap Simon Petrus di Danau Tiberias,saat akan sarapan bersama Yesus ?", jawaban: "153ekor ikan (Yohanes 21:11)" },
  { nomor: 23, soal: "Siapakah nama murid Yesus yang diketahui menikah dalam alkitab?", jawaban: "Petrus (Matius 8:14-17)" },
  { nomor: 24, soal: "Dimana tempat Yakub bergumul dengan Tuhan hingga sendi pangkal pahanya terpelecok?", jawaban: "Pniel (Kejadian 32:22-32)" },
  { nomor: 25, soal: "Apa nama sungai yang dibelah oleh Elisa dengan menggunakan jubah Elia?", jawaban: "Sungai Yordan (2raja-raja 2:14)" },
  { nomor: 26, soal: "Dalam kitab wahyu,jemaat mana yang disebutkan suam-suam kuku?", jawaban: "Laodikia (wahyu 3:14-16)" },
  { nomor: 27, soal: "Apa nama tempat dimana orang Israel bertengkar dan mencobai Tuhan dengan mengatakan \"adakah Tuhan di tengah-tengah kita atau tidak?\"?", jawaban: "Masa dan Meriba (keluaran 17:7)" },
  { nomor: 28, soal: "Dimanakah tempat yang terdapat 12mata air dan 7pohon korma?", jawaban: "Elim (keluaran 15:27)" },
  { nomor: 29, soal: "Apa nama tempat asal Lidia si penjual kain ungu?", jawaban: "Tiatira (Kisah para rasul 16:14)" },
  { nomor: 30, soal: "Siapakah nama raja terakhir Yehuda?", jawaban: "Zedekia (2raja-raja 24)" },
  { nomor: 31, soal: "Siapakah Raja yang jatuh dari kisi-kisi kamar atas rumahnya?", jawaban: "Ahazia" },
  { nomor: 32, soal: "Siapakah Raja kedua Israel?", jawaban: "Daud (2Sam 2:8)" },
  { nomor: 33, soal: "Siapakah Raja Salem yang disebutkan sebagai Imam Allah yang Maha tinggi?", jawaban: "Melkisedek (Kej 14:18)" },
  { nomor: 34, soal: "Siapakah Raja yang ditampar malaikat kemudian mayatnya dimakan cacing?", jawaban: "Herodes (Kisah 12:20-23)" },
  { nomor: 35, soal: "Siapakah istri Raja Israel yang mayatnya dimakan anjing?", jawaban: "Izebel (2Raja-raja 9:36)" },
  { nomor: 36, soal: "Siapakah Raja Sikhem yang ditimpa batu kilangan oleh seorang wanita?", jawaban: "Abimelekh (Hakim-hakim 9:50-57)" },
  { nomor: 37, soal: "Siapakah Raja Gerar yang tertarik dengan Sara,istri Abraham?", jawaban: "Abimelekh (Kej 20:2)" },
  { nomor: 38, soal: "Siapakah Hakim yang membunuh 600orang Filistin dengan tongkat penghalau lembu?", jawaban: "Samgar (Hakim-hakim 3:31)" },
  { nomor: 39, soal: "Siapakah nama suami dari seorang hakim wanita yang juga seorang nabiah?", jawaban: "Lapidot (Hakim-hakim 4:4)" },
  { nomor: 40, soal: "Siapakah nabi yang disebutkan dalam Alkitab berkepala botak?", jawaban: "Elisa (2Raja-raja 2:23)" },
  { nomor: 41, soal: "Berapakah jumlah beruang yang keluar dari hutan untuk mencabik anak-anak yang telah mencemooh seorang nabi yang berkepala botak tersebut?", jawaban: "dua (2Raja-raja 2:24)" },
  { nomor: 42, soal: "Berapakah jumlah anak-anak yang dicabik beruang karena mereka mencemooh seorang nabi berkepala botak?", jawaban: "42(2Raja-raja 2:24)" },
  { nomor: 43, soal: "Siapakah yang disuruh oleh Nabi Yeremia untuk menuliskan kitab Yeremia?", jawaban: "Barukh (Yer 36:4)" },
  { nomor: 44, soal: "Siapakah nabi yang jatuh dari kursi ketika mendengar kabar kedua anaknya meninggal dan tabut Allah dirampas?", jawaban: "Eli (1Sam 4:18)" },
  { nomor: 45, soal: "Siapakah nama anak Nabi Nuh yang melihat ayahnya telanjang?", jawaban: "Ham (Kej 9:22)" },
  { nomor: 46, soal: "Nabi yang menjadi perantara Raja Hizkia dengan Tuhan?", jawaban: "Yesaya (2Raja-raja 20)" },
  { nomor: 47, soal: "Apa nama pohon yang ditumbuhkan Tuhan untuk menaungi Yunus?", jawaban: "Pohon Jarak (Yunus 4:6)" },
  { nomor: 48, soal: "Siapakah rasul yang dibunuh oleh Herodes?", jawaban: "Yakobus (Kisah 12:2)" },
  { nomor: 49, soal: "Siapakah nama nabi palsu yang juga tukang sihir di pulau Siprus,yang menghalangi gubernur itu utk mendengarkan Firman Allah dari Paulus dan Barnabas?", jawaban: "Elimas /Baryesus (Kis 13:4-12)" },
  { nomor: 50, soal: "Siapakah nama murid pengganti Yudas Iskariot?", jawaban: "Matias (Kis 1:26)" },
  { nomor: 51, soal: "Siapakah nama seorang yang lain yang diusulkan untuk menggantikan Yudas?", jawaban: "Yustus /Barsabas /Yusuf (Kisah 1:23)" },
  { nomor: 52, soal: "Siapakah nama hamba imam besar yang telinganya putus karena Petrus?", jawaban: "Malkhus (Yoh 18:10)" },
  { nomor: 53, soal: "Siapakah nama murid Tuhan yang diberikan penglihatan untuk mencari Saulus di rumah Yudas?", jawaban: "Ananias (Kisah 9:10-11)" },
  { nomor: 54, soal: "Dimanakah bahtera Nuh kandas?", jawaban: "Gunung Ararat" },
  { nomor: 55, soal: "Dimanakah Sara dikuburkan?", jawaban: "Gua Makhpela (Kejadian 23)" },
  { nomor: 56, soal: "Dimanakah gua persembunyian Daud dari Saul?", jawaban: "Gua Adulam (1Sam 22:1)" },
  { nomor: 57, soal: "Dimanakah Yesus membangkitkan anak laki-laki seorang janda?", jawaban: "Nain (Lukas 7:11)" },
  { nomor: 58, soal: "Nama asal Daerah sida-sida yang dibaptis oleh Filipus?", jawaban: "Etiopia" },
  { nomor: 59, soal: "Di atas gunung apakah Musa mati?", jawaban: "Gunung Nebo (Ulangan 34:1-5)" },
  { nomor: 60, soal: "Siapakah nama Ratu Etiopia yang sida-sidanya dibaptis oleh salah satu murid Yesus?", jawaban: "Sri Kandake (Kisah 8:27)" },
  { nomor: 61, soal: "Siapakah Raja yang diperpanjang umurnya 15tahun?", jawaban: "Hizkia (2Raja-raja 20:6)" },
  { nomor: 62, soal: "Apa nama lain Yusuf yang diberikan oleh Firaun?", jawaban: "Zafnat Paaneah (Kej 41:45)" },
  { nomor: 63, soal: "Siapakah nama anak perempuan Raja Saul yang mnejadi istri Raja Daud?", jawaban: "Mikhal (1Samuel 18:20)" },
  { nomor: 64, soal: "Siapakah nama Raja yang pada masa pemerintahannya terjadi gempa bumi?", jawaban: "Uzia (Amos 1:1)" },
  { nomor: 65, soal: "Siapakah nama Ratu yang digantikan kedudukannya oleh Ester?", jawaban: "Ratu Wasti (Ester 2:17)" },
  { nomor: 66, soal: "Siapakah nama pembesar Raja Ahasyweros yang mati di tiang gantungan yang dibuatnya sendiri?", jawaban: "Haman (Ester 7:10)" },
  { nomor: 67, soal: "Nehemia membangun kembali tembok Yerusalem pada masa pemerintahan Raja siapa?", jawaban: "Artahsasta (Neh 2:1)" },
  { nomor: 68, soal: "Siapakah nama ayah Simson?", jawaban: "Manoah (Hakim-hakim 13:2)" },
  { nomor: 69, soal: "Siapakah nama hakim yang bernazar,sehingga akhirnya ia mengorbankan anak perempuannya untuk Tuhan?", jawaban: "Yefta (Hakim-hakim 11:29-40)" },
  { nomor: 70, soal: "Siapakah Nabi yang dihukum mati oleh Raja Yoyakim?", jawaban: "Nabi Uria (Yer 26:23)" },
  { nomor: 71, soal: "Siapakah nabiah perjanjian baru yang sudah lanjut umurnya,dan mengucap syukur dan berbicaratentang Yesus?", jawaban: "Hana (Luk 2:36-38)" },
  { nomor: 72, soal: "Siapakah nama bidan yang takut akan Tuhan sehingga tidak menuruti perintah Firaun untuk membunuh anak laki-laki Israel?", jawaban: "Pua dan Sifra (Kel 1:15-17)" },
  { nomor: 73, soal: "Siapakan Nabi yang mabuk pertama kali oleh anggur?", jawaban: "Nuh (Kej 9:21)" },
  { nomor: 74, soal: "Nama salah satu anak nabi Hosea?", jawaban: "Lo-Ruhama (Hosea 1:6)" },
  { nomor: 75, soal: "Nama salah satu putri Ayub?", jawaban: "Kezia/Yemima/Karenhapukh (Ayub 42:14)" },
  { nomor: 76, soal: "Siapakah nabi besar yang memakan gulungan kitab dan rasanya manis seperti madu?", jawaban: "Yehezkiel (3:3)" },
  { nomor: 77, soal: "Apa makanan dari Yohanes pembaptis?", jawaban: "Belalang dan madu hutan (Markus 1:6)" },
  { nomor: 78, soal: "Berapakah uang yang didapatkan oleh Simon Petrus di dalam mulut ikan pancingannya?", jawaban: "4 Dirham (Mat 17:27)" },
  { nomor: 79, soal: "Dengan berapa keping perak,Yudas menjual Yesus?", jawaban: "30keping uang perak (Mat 26:15)" },
  { nomor: 80, soal: "Siapakah nama ketiga murid yang ikut berdoa dengan Yesus di taman Getsemani?", jawaban: "Yohanes, Yakobus,Petrus (Mat 26:37)" },
  { nomor: 81, soal: "Siapakah nama guru dari rasul Paulus?", jawaban: "Gamaliel (Kis 5:26-42)" },
  { nomor: 82, soal: "Siapakah nama perwira pasukan Italia yang dibaptis oleh Petrus?", jawaban: "Kornelius (Kisah 10)" },
  { nomor: 83, soal: "Sipakah nama orang lumpuh dari Lida yang disembuhkan oleh Petrus?", jawaban: "Eneas (Kis 9:32-35)" },
  { nomor: 84, soal: "Dimana Nabi Elisa membangkitkan seorang anak?", jawaban: "sunem (2Raja-raja 4:8-37)" },
  { nomor: 85, soal: "Dimana tempat Yohanes mendapatkan penglihatan mengenai akhir zaman?", jawaban: "Pulau Patmos (Wahyu 1:9)" },
  { nomor: 86, soal: "Di kota manakah Barnabas disebut dewa Zeus dan Paulus disebut dewa Hermes?", jawaban: "Listra (Kis 14:12)" },
  { nomor: 87, soal: "Dimanakah Paulus mencukur rambutnya?", jawaban: "Kengkrea (Kis 18:18)" },
  { nomor: 88, soal: "Setelah membunuh Habel,Kain menetap dimana?", jawaban: "Tanah Nod (Kej 4:16)" },
  { nomor: 89, soal: "Dimanakah abraham akan mempersembahkan anaknya,Ishak?", jawaban: "Tanah Moria (Kel 22:2)" },
  { nomor: 90, soal: "Dimanakah Terah meninggal?", jawaban: "Haran (Kej 11:32)" },
  { nomor: 91, soal: "Apa yang diciptakan pada hari ke-5?", jawaban: "Binatang air dan udara (kej 1:20-22)" },
  { nomor: 92, soal: "Sebutkan nama 4sungai yang mengaliri taman Eden!", jawaban: "Pison,Gihon,Efrat,Tigris (kej 2:11-14)" },
  { nomor: 93, soal: "Siapakah nama kedua anak Yusuf,sang raja Mesir?", jawaban: "Manasye dan Efraim" },
  { nomor: 94, soal: "Apakah tulah ke-5?", jawaban: "Penyakit sampar pada ternak" },
  { nomor: 95, soal: "Warna apakah yang pertama kali disebutkan dalam alkitab?", jawaban: "Hijau (Kej 1:30)" },
  { nomor: 96, soal: "Siapakah nama saudara Yusuf yang mengusulkan agar Yusuf dimasukan ke dalam sumur?", jawaban: "Ruben (Kej 37:19-22)" },
  { nomor: 97, soal: "Sebutkan 2tokoh Alkitab yang tidak mengalami kematian!", jawaban: "Henokh (Kej 5:23-24),Elia (2Raja-Raja 2:11)" },
  { nomor: 98, soal: "Berapa lama air bah menguasai bumi?", jawaban: "150hari (Kej 7:24)" },
  { nomor: 99, soal: "Kayu apa yang digunakan sebagai bahan dasar pembuatan bahtera?", jawaban: "Kayu Gofir (Kej 6:14)" },
  { nomor: 100, soal: "Dengan apakah barah Raja Hizkia disembuhkan?", jawaban: "Kue Ara (2Raja-Raja20:7)" },
  { nomor: 101, soal: "Berapakah jumlah pengintai yang dikirim Musa untuk mengintai tanah Kanaan?", jawaban: "12(Bil 13:1-16)" },
  { nomor: 102, soal: "Siapakah nama istri dari Saul?", jawaban: "Ahinoam (1Samuel 14)" },
  { nomor: 103, soal: "Berapakah ukuran panjang,lebar,dan tinggi bahtera Nuh?", jawaban: "panjang 300hasta,lebar 50hasta, tinggi 30hasta (kej 6:15)" },
  { nomor: 104, soal: "Berapa kali bangsa Israel mengelilingi tembok Yerikho hingga runtuh?", jawaban: "13kali (Yosua 6)" },
  { nomor: 105, soal: "Berapa bakul yang tersisa ketika Tuhan Yesus memberi makan 4000orang?", jawaban: "7bakul (Mat 15:37)" },
  { nomor: 106, soal: "Siapakah nama hakim Israel yang mempunyai 70orang anak laki-laki?", jawaban: "Gideon (hak 8:30)" },
  { nomor: 107, soal: "Siapakah yang mengakui dosanya kepada malaikat Tuhan,yang pada mulanya hanya dilihat oleh keledainya?", jawaban: "Bileam (Bil 22:34)" },
  { nomor: 108, soal: "Ada seorang pemilik kebun anggur yang difitnah oleh istri seorang Raja Israel dan kemudian dihukum mati dengan cara dilempar batu,lalu kebun anggurnya direbut.Siapakah nama pemilik kebun anggur tersebut?", jawaban: "Nabot (1Raja-Raja 21)" },
  { nomor: 109, soal: "Aku seorang wanita.Suamiku yang pertama berlaku sangat jahat sehingga Tuhan mengambil nyawaNya.Kemudia aku dinikahkan dengan adik dari suamiku tadi,tapi Tuhan mengambil nyawaNya juga.Setelah itu aku menjebak mertuaku sehingga aku mengandung dan melahirkan sepasang anak kembar.Siapakah aku?", jawaban: "Tamar (Kej 38)" },
  { nomor: 110, soal: "Siapakah Raja yang juga penyair dan pemain musik,yang telah mempermalukan istrinya dengan meloncat-loncat serta menari-nari di jalan?", jawaban: "Daud (2Sam 6:16,20)" },
  { nomor: 111, soal: "Siapakah nabi yang membuat masakan beracun di sebuah kuali,dapat dimakan dengan melemparkan tepung ke dalamnya?", jawaban: "Elisa (2Raja-raja 4:41)" },
  { nomor: 112, soal: "Dimanakah murid-murid Tuhan untuk pertama kalinya disebut orang Kristen?", jawaban: "Antiokhia (Kis 11:26)" },
  { nomor: 113, soal: "Siapakah nama mertua laki-laki dari Rut?", jawaban: "Elimelekh (Rut 1)" },
  { nomor: 114, soal: "Burung apakah yang pertama kali dilepaskan oleh Abraham ketika air bah mulai surut?", jawaban: "Gagak (Kej 8:7)" },
  { nomor: 115, soal: "Sebutkan 4binatang terkecil di bumi yang disebutkan dalam kitab Amsal sebagai makhluk cekatan?", jawaban: "Semut,pelanduk,belalang,cicak (Ams 30:24-28)" },
  { nomor: 116, soal: "Di pulau manakah Paulus dipagut tangannya oleh seekor ular berbisa?", jawaban: "Malta (kis 28:3)" },
  { nomor: 117, soal: "Siapakah keturunan Saul yang mengutuki Daud?", jawaban: "Simei (2Sam 16:5)" },
  { nomor: 118, soal: "Siapakah nama istri Abraham yang kedua setelah kematian Sara?", jawaban: "Ketura (Kejadian 25:1-4)" },
  { nomor: 119, soal: "Siapakah nama putra Daud dari Hagit yang memberontak melawannya karena ingin merebut tahtanya?", jawaban: "Adonia (I Raja-raja 1)" },
  { nomor: 120, soal: "Henokh merupakan salah satu orang yang tidak mengalami kematian karena dia secara langsung diangkat oleh Allah.Siapakah nama kakek dari Henokh?", jawaban: "Mahalaleel (Kejadian 5)" },
  { nomor: 121, soal: "Siapakah nama salah satu anak dari nabi Hosea?", jawaban: "Yizreel,Lo-Ami,Lo Ruhama (Hosea 1)" },
  { nomor: 122, soal: "Dimanakah Paulus memberitakan injil sehingga seorang kepala rumah ibadat bernama Krispus bertobat?", jawaban: "Korintus (Roma 18)" },
  { nomor: 123, soal: "Siapakah nama seorang perempuan sundal yang menjadi istri dari nabi Hosea?", jawaban: "Gomer (Hosea 1)" },
  { nomor: 124, soal: "Siapakah nama seorang wanita yang membunuh semua keturunan raja setelah sang raja mati agar dia dapat memerintah kerajaan tersebut?", jawaban: "Atalya (II Raja-raja 11)" },
  { nomor: 125, soal: "Siapakah nama anak dari nabi Yesaya?", jawaban: "Maher-Syalal Hash-Bas (yesaya 8)" },
  { nomor: 126, soal: "Siapakah nama rekan sekerja Paulus yang disebut sebagai dewa Zeus di Listra?", jawaban: "Barnabas (Kisah 14:12)" },
  { nomor: 127, soal: "Dimanakah daerah tempat saul dilahirkan?", jawaban: "Gibea (I Samuel 11:4)" },
  { nomor: 128, soal: "Siapakah nama ibu dari Timotius?", jawaban: "Eunike (II Timotius 1:5)" },
  { nomor: 129, soal: "Tulisan di dinding istana raja Belsyazar yang kemudian diterjemahkan oleh Daniel?", jawaban: "Mene mene tekel ufarsin (Daniel 5:25)" },
  { nomor: 130, soal: "Apa bunyi dari Matius 28:19–20?", jawaban: "Karena itu pergilah,jadikanlah semua bangsa murid-Ku dan baptislah mereka dalam nama Bapa dan Anak dan Roh Kudus,dan ajarlah mereka melakukan segala sesuatu yang telah Kuperintahkan kepadamu.Dan ketahuilah,Aku menyertai kamu senantiasa sampai kepada akhir zaman." },
  { nomor: 131, soal: "Apa arti Golgota?", jawaban: "Tempat Tengkorak" },
  { nomor: 132, soal: "Apa arti \"Eli-Eli lama sabakhtani\"dan terdapat pada?", jawaban: "Allah-Ku,Allah-Ku,mengapa Engkau meninggalkan Aku?(Matius 27:46)" },
  { nomor: 133, soal: "Siapa nama murid yang paling dikasihi Yesus?", jawaban: "Yohanes" },
  { nomor: 134, soal: "Pada umur berapakah Yesus mulai mengajar?", jawaban: "12tahun" },
  { nomor: 135, soal: "Apa arti \"INRI\"?", jawaban: "Inilah Raja Orang Yahudi" },
  { nomor: 136, soal: "Dimanakah Yesus disalibkan?", jawaban: "Di Bukit Golgota" },
  { nomor: 137, soal: "Tuhan Yesus dijual seharga?", jawaban: "30keping perak" },
  { nomor: 138, soal: "Di mana Tuhan Yesus ditangkap?", jawaban: "Taman Getsemani" },
  { nomor: 139, soal: "Sesudah menyanyikan nyanyian pujian,Yesus dan murid-murid-Nya pergi ke bukit?", jawaban: "Bukit Zaitun" },
  { nomor: 140, soal: "Berapa kali Petrus menyangkal Yesus?", jawaban: "3kali sebelum ayam berkokok" },
  { nomor: 141, soal: "Sebutkan nama-nama ke-12murid Tuhan Yesus!", jawaban: "Simon Petrus,Andreas,Yakobus,Yohanes, Filipus,Bartolomeus,Tomas,Matius,Yakobus anak Alfeus,Simon orang Zelot,Yudas anak Yakobus,Yudas Iskariot" },
  { nomor: 142, soal: "Apa arti Kefas?", jawaban: "Petrus" },
  { nomor: 143, soal: "Apa arti Mesias?", jawaban: "Kristus" },
  { nomor: 144, soal: "Apa arti Rabi?", jawaban: "Guru" },
  { nomor: 145, soal: "Siapakah yang mengkhianati Yesus?", jawaban: "Yudas Iskariot" },
  { nomor: 146, soal: "Siapakah yang meminta kepada Yesus bukan untuk memerintah melainkan untuk melayani?", jawaban: "Yakobus dan Yohanes" },
  { nomor: 147, soal: "Dari mana Yesus berasal?", jawaban: "Nazaret" },
  { nomor: 148, soal: "Apa arti Boanerges?", jawaban: "Anak-anak guruh" },
  { nomor: 149, soal: "Siapakah yang membaptis Yesus?", jawaban: "Yohanes Pembaptis" },
  { nomor: 150, soal: "Sebutkan 4sungai yang terdapat dalam Taman Eden!", jawaban: "Pison,Gihon,Tigris,dan Efrat" },
  { nomor: 151, soal: "Siapakah yang menjadi tiang garam?", jawaban: "Istri Lot" },
  { nomor: 152, soal: "Siapa nama ibu Ismail?", jawaban: "Hagar" },
  { nomor: 153, soal: "Apa arti Ishak?", jawaban: "Tertawa" },
  { nomor: 154, soal: "Sebutkan ke-12anak-anak Yakub!", jawaban: "Ruben,Simeon,Lewi,Yehuda,Dan,Naftali,Gad,Asyer, Isakhar,Zebulon,Yusuf,Dina" },
  { nomor: 155, soal: "Sebutkan ke-10tulah!", jawaban: "Air menjadi darah,katak,nyamuk,lalat pikat,penyakit sampar pada ternak,barah,hujan es,belalang,gelap gulita,kematian anak sulung" },
  { nomor: 156, soal: "Siapa yang membawa orang Israel keluar dari Tanah Mesir?", jawaban: "Musa" },
  { nomor: 157, soal: "Siapa nama istri Musa?", jawaban: "Zipora" },
  { nomor: 158, soal: "Di mana terdapat hukum yang terutama?", jawaban: "Matius 22:37–40" },
  { nomor: 159, soal: "Apa bunyi Wahyu 2:10b?", jawaban: "Hendaklah engkau setia sampai mati dan Aku akan mengaruniakan kepadamu mahkota kehidupan" },
  { nomor: 160, soal: "Siapakah yang diangkat oleh Mordekhai sebagai anaknya?", jawaban: "Ester" },
  { nomor: 161, soal: "Sebutkan ke-9buah Roh dan terdapat pada?", jawaban: "Kasih,sukacita,damai sejahtera,kesabaran, kemurahan,kebaikan,kesetiaan,kelemahlembutan,penguasaan diri (Galatia 5:22–23)" },
  { nomor: 162, soal: "Apa arti Sola Gratia?", jawaban: "Hanya oleh anugerah kita diselamatkan" },
  { nomor: 163, soal: "Apa arti Sola Fide?", jawaban: "Hanya oleh iman kita dibenarkan" },
  { nomor: 164, soal: "Apa arti Sola Scriptura?", jawaban: "Alkitab adalah Firman Allah" },
  { nomor: 165, soal: "Apa arti Alfa dan Omega?", jawaban: "Yang awal dan yang akhir" },
  { nomor: 166, soal: "Berapa jumlah kitab PL dan PB?", jawaban: "PL 39kitab dan PB 27kitab" },
  { nomor: 167, soal: "Terdiri atas berapa pasal Kitab Obaja?", jawaban: "1pasal" },
  { nomor: 168, soal: "Apa arti Petrus?", jawaban: "Batu karang" },
  { nomor: 169, soal: "Di manakah terdapat Doa Bapa Kami?", jawaban: "Matius 6:9–13" },
  { nomor: 170, soal: "Apa arti Samuel?", jawaban: "Anak yang diminta" },
  { nomor: 171, soal: "Siapa nama istri Uria?", jawaban: "Batsyeba" },
  { nomor: 172, soal: "Apa nama kitab sebelum Mikha?", jawaban: "Yunus" },
  { nomor: 173, soal: "Di dalam KJ nomor berapakah lagu \"Pada Kaki Salib-Mu\"?", jawaban: "KJ No.368" },
  { nomor: 174, soal: "Apa bunyi 1Timotius 4:12?", jawaban: "Jangan seorang pun menganggap engkau rendah karena engkau muda,jadilah teladan bagi orang-orang percaya dalam perkataan,tingkah laku,kasih,kesetiaan, dan kesucian" },
  { nomor: 175, soal: "Siapakah yang dimasukkan ke dalam perapian yang menyala-nyala?", jawaban: "Sadrakh,Mesakh,dan Abednego" },
  { nomor: 176, soal: "Apa arti Efrata?", jawaban: "Terbukalah" },
  { nomor: 177, soal: "Apa arti Hosea?", jawaban: "Hamba Tuhan" },
  { nomor: 178, soal: "Apa arti Rut?", jawaban: "Teman atau sahabat" },
  { nomor: 179, soal: "Dalam Filipi 1:21dikatakan \"Karena bagiku hidup adalah ...dan mati adalah ...\"?", jawaban: "Kristus dan keuntungan" },
  { nomor: 180, soal: "Sebutkan tanda-tanda yang terjadi saat Yesus mati!", jawaban: "Gelap gulita,Bait Suci terbelah dua,gempa bumi,bukit-bukit batu terbelah" },
  { nomor: 181, soal: "\"Takut akan TUHAN adalah permulaan pengetahuan...\"terdapat di mana?", jawaban: "Amsal 1:7" },
  { nomor: 182, soal: "Apa arti \"Ora et labora\"?", jawaban: "Berdoa dan bekerja" },
  { nomor: 183, soal: "Apa arti Matius?", jawaban: "Pemberian Allah" },
  { nomor: 184, soal: "Apakah pekerjaan Matius sebelum mengikut Yesus?", jawaban: "Pemungut cukai" },
  { nomor: 185, soal: "Kepada siapakah Injil Lukas ditujukan?", jawaban: "Theofilus" },
  { nomor: 186, soal: "Yesus lahir di kota?", jawaban: "Betlehem" },
  { nomor: 187, soal: "Mujizat air menjadi anggur terjadi di kota?", jawaban: "Kana" },
  { nomor: 188, soal: "Siapakah penulis Kitab Wahyu?", jawaban: "Yohanes" },
  { nomor: 189, soal: "Siapakah penulis Kitab Kisah Para Rasul?", jawaban: "Lukas" },
  { nomor: 190, soal: "\"Hormatilah ayah dan ibumu\"adalah hukum Taurat ke berapa?", jawaban: "Hukum Taurat ke-5" },
  { nomor: 191, soal: "\"Terang\"diciptakan pada hari ke berapa?", jawaban: "Hari pertama" },
  { nomor: 192, soal: "Berapakah jumlah pasal dalam Kitab Kejadian?", jawaban: "50pasal" },
  { nomor: 193, soal: "Apa yang dimaksud dengan Imago Dei?", jawaban: "Segambar dan serupa dengan Allah" },
  { nomor: 194, soal: "Berapa tahun bangsa Israel menuju Tanah Kanaan?", jawaban: "40tahun" },
  { nomor: 195, soal: "Di manakah Tuhan Yesus dibaptis?", jawaban: "Sungai Yordan" },
  { nomor: 196, soal: "Pada umur berapakah Tuhan Yesus disunat?", jawaban: "8hari" },
  { nomor: 197, soal: "Melalui siapakah semua bangsa memperoleh kelepasan?", jawaban: "Abraham" },
  { nomor: 198, soal: "Apa arti Zet?", jawaban: "Pengganti" },
  { nomor: 199, soal: "Apa arti Abraham?", jawaban: "Bapa segala orang percaya" },
  { nomor: 200, soal: "Sebutkan nama anak-anak Nuh!", jawaban: "Sem,Ham,dan Yafet" },
  { nomor: 201, soal: "Siapakah yang menjual hak kesulungannya demi semangkuk kacang merah?", jawaban: "Esau" },
  { nomor: 202, soal: "Apa arti Yakub?", jawaban: "Penipu" },
  { nomor: 203, soal: "Apa arti Esau?", jawaban: "Berbulu" },
  { nomor: 204, soal: "Apa arti Musa?", jawaban: "Anak yang diangkat dari air" },
  { nomor: 205, soal: "Apa sajakah yang dipersembahkan oleh orang-orang Majus dari timur?", jawaban: "Emas,kemenyan,dan mur" },
  { nomor: 206, soal: "Apakah yang dikatakan di dalam Yakobus 1:8?", jawaban: "Sebab orang yang mendua hati tidak akan tenang dalam hidupnya" },
  { nomor: 207, soal: "\"Hai pemalas,pergilah kepada semut,perhatikanlah lakunya dan jadilah bijak.\"Di mana nats ini terletak?", jawaban: "Amsal 6:6" },
  { nomor: 208, soal: "Berapa kalikah kata \"mengajar\"digunakan dalam Kitab Matius?", jawaban: "9kali" },
  { nomor: 209, soal: "Siapakah yang dijadikan sebagai penjala manusia?", jawaban: "Simon Petrus" },
  { nomor: 210, soal: "Mengapa Yesus disebut sebagai Guru Agung?", jawaban: "Karena hakekat pribadi-Nya sendiri" },
  { nomor: 211, soal: "Pada hari ke berapakah Tuhan menciptakan manusia?", jawaban: "Hari ke-6" },
  { nomor: 212, soal: "Dalam Ibrani 7:2,apakah arti nama Melkisedek?", jawaban: "Raja kebenaran dan Raja damai sejahtera" },
  { nomor: 213, soal: "Siapakah yang menggantikan Yesus memikul salib-Nya?", jawaban: "Simon dari Kirene" },
  { nomor: 214, soal: "Berapa orang yang dipilih untuk melayani orang miskin?", jawaban: "7orang" },
  { nomor: 215, soal: "Siapakah nama ibu Benyamin?", jawaban: "Rahel" },
  { nomor: 216, soal: "Apa arti Pentakosta?", jawaban: "Hari turunnya Roh Kudus" },
  { nomor: 217, soal: "Di manakah pasal dan ayat terpendek dalam Alkitab?", jawaban: "Mazmur 117:1–2" },
  { nomor: 218, soal: "Apa bunyi Mazmur 119:105?", jawaban: "Firman-Mu itu pelita bagi kakiku dan terang bagi jalanku" },
  { nomor: 219, soal: "Di manakah Hukum Taurat selain Keluaran 20?", jawaban: "Ulangan 4:11–12" },
  { nomor: 220, soal: "Apa inti dari seluruh Hukum Taurat?", jawaban: "Kasih" },
  { nomor: 221, soal: "Terbuat dari apakah bahtera Nuh?", jawaban: "Kayu gofir" },
  { nomor: 222, soal: "Di manakah bahtera Nuh kandas?", jawaban: "Gunung Ararat" },
  { nomor: 223, soal: "Berapakah ukuran bahtera Nuh?", jawaban: "300hasta panjangnya,50hasta lebarnya,dan 30hasta tingginya" },
  { nomor: 224, soal: "Burung apa yang turun saat Yesus dibaptis?", jawaban: "Burung merpati" },
  { nomor: 225, soal: "Apa bunyi Ibrani 11:1?", jawaban: "Iman adalah dasar dari segala sesuatu yang kita harapkan dan bukti dari segala sesuatu yang tidak kita lihat" },
  { nomor: 226, soal: "\"Pergaulan yang buruk merusakkan kebiasaan yang baik\"terdapat dalam kitab apa?", jawaban: "1Korintus 15:33" },
  { nomor: 227, soal: "Siapakah yang mati sehingga Petrus dilepaskan dari penjara?", jawaban: "Yakobus" },
  { nomor: 228, soal: "Siapakah yang disebut pasukan Italia?", jawaban: "Kornelius" },
  { nomor: 229, soal: "Siapakah yang terbunuh saat Saulus hadir?", jawaban: "Stefanus" },
  { nomor: 230, soal: "Apa yang dikenakan Adam dan Hawa setelah berdosa?", jawaban: "Daun pohon ara" },
  { nomor: 231, soal: "Berapa lama air bah menutupi bumi?", jawaban: "150hari" },
  { nomor: 232, soal: "Apa nama kasih antara orang tua dan anak?", jawaban: "Storge" },
  { nomor: 233, soal: "Siapakah murid Yesus yang ingin dibasuh kakinya?", jawaban: "Petrus" },
  { nomor: 234, soal: "Siapakah penjual kain ungu?", jawaban: "Lidya" },
  { nomor: 235, soal: "Siapa nama ayah Daud?", jawaban: "Isai" },
  { nomor: 236, soal: "Siapakah hakim perempuan di Israel?", jawaban: "Debora" },
  { nomor: 237, soal: "Siapakah perempuan yang menyelamatkan bangsanya dari pembantaian?", jawaban: "Ester" },
  { nomor: 238, soal: "Siapa orang tua Martin Luther?", jawaban: "Hans Luther dan Katerina von Bora" },
  { nomor: 239, soal: "Apa arti Daud?", jawaban: "Yang dikasihi" },
  { nomor: 240, soal: "Apa arti Yehezkiel?", jawaban: "Allah menguatkan" },
  { nomor: 241, soal: "Apa arti Gideon?", jawaban: "Pahlawan yang gagah berani" },
  { nomor: 242, soal: "Apa arti Onesimus?", jawaban: "Yang berguna" },
  { nomor: 243, soal: "Apa arti Adam?", jawaban: "Yang dibuat dari tanah" },
  { nomor: 244, soal: "Apa arti Akwila?", jawaban: "Burung rajawali" },
  { nomor: 245, soal: "Apa arti Talita kum?", jawaban: "Hai anak perempuan,bangkitlah" },
  { nomor: 246, soal: "Siapa pengarang lagu KJ 64\"Bila Kulihat Bintang Gemerlapan\"?", jawaban: "Gustaf Boberg" },
  { nomor: 247, soal: "Pada usia berapa Yesus wafat?", jawaban: "30tahun" },
  { nomor: 248, soal: "Di manakah Taman Getsemani?", jawaban: "Seberang Sungai Kidron" },
  { nomor: 249, soal: "Apa mukjizat pertama Yesus?", jawaban: "Mengubah air menjadi anggur" },
  { nomor: 250, soal: "Siapakah murid yang memotong telinga hamba Imam Besar?", jawaban: "Petrus" },
  { nomor: 251, soal: "Siapakah nama hamba Imam Besar itu?", jawaban: "Malkhus" },
  { nomor: 252, soal: "Apa hukum yang terutama dan pertama?", jawaban: "Kasihilah Tuhan Allahmu dengan segenap hatimu, jiwamu,dan akal budimu" },
  { nomor: 253, soal: "Siapakah yang meminta jenazah Yesus kepada Pilatus?", jawaban: "Yusuf dari Arimatea" },
  { nomor: 254, soal: "Bersama siapa Yusuf mengafani Yesus?", jawaban: "Nikodemus" },
  { nomor: 255, soal: "Dengan apakah Maria mengolesi kaki Yesus?", jawaban: "Minyak narwastu murni" },
  { nomor: 256, soal: "Siapa dua murid yang datang ke kubur lalu pulang lebih dulu?", jawaban: "Simon Petrus dan Yohanes" },
  { nomor: 257, soal: "Apa yang Yesus lakukan sebelum Perjamuan Terakhir?", jawaban: "Membasuh kaki murid-murid" },
  { nomor: 258, soal: "Ke mana malaikat menyuruh murid-murid bertemu Yesus?", jawaban: "Galilea" },
  { nomor: 259, soal: "Apa yang dilakukan sebelas murid saat Yesus menampakkan diri?", jawaban: "Sedang makan bersama" },
  { nomor: 260, soal: "Seseorang harus dilahirkan dari apa menurut Yesus?", jawaban: "Air dan Roh" },
  { nomor: 261, soal: "Siapa dua tokoh PL yang tidak mati?", jawaban: "Henokh dan Elia" },
  { nomor: 262, soal: "Siapa murid di Danau Tiberias saat Yesus menampakkan diri?", jawaban: "Simon Petrus,Tomas,Natanael,Yakobus,dan Yohanes" },
  { nomor: 263, soal: "Berapa jumlah ikan hasil tangkapan di Danau Tiberias?", jawaban: "153ekor" },
  { nomor: 264, soal: "Siapakah nabi yang dipenggal kepalanya?", jawaban: "Yohanes Pembaptis" },
  { nomor: 265, soal: "Di mana orang buta disuruh membasuh diri?", jawaban: "Kolam Siloam" },
  { nomor: 266, soal: "Siapakah yang disembah sebagai dewa setelah dipatuk ular?", jawaban: "Paulus" },
  { nomor: 267, soal: "Siapakah orang tertua di Alkitab?", jawaban: "Metusalah" },
  { nomor: 268, soal: "Siapakah yang dibebaskan malaikat dari penjara?", jawaban: "Petrus" },
  { nomor: 269, soal: "Siapakah juru minuman raja yang membangun tembok Yerusalem?", jawaban: "Nehemia" },
  { nomor: 270, soal: "Suku Israel manakah yang menjadi imam?", jawaban: "Lewi" },
  { nomor: 271, soal: "Siapakah misionaris terbesar PB?", jawaban: "Paulus" },
  { nomor: 272, soal: "Di kota manakah Yesus diurapi dengan minyak mahal?", jawaban: "Betania" },
  { nomor: 273, soal: "Siapakah murid yang menyebut pengurapan itu pemborosan?", jawaban: "Yudas Iskariot" },
  { nomor: 274, soal: "Apa kata Yesus saat membagi roti?", jawaban: "Ambillah,makanlah,inilah tubuh-Ku" },
  { nomor: 275, soal: "Ke mana Yudas membuang 30keping perak?", jawaban: "Bait Suci" },
  { nomor: 276, soal: "Untuk apa uang itu digunakan para imam?", jawaban: "Membeli tanah tukang periuk" },
  { nomor: 277, soal: "Siapakah yang mengirim pesan kepada Pilatus agar tidak mencampuri perkara Yesus?", jawaban: "Istri Pilatus" },
  { nomor: 278, soal: "Di manakah terdapat sumur Yakub?", jawaban: "Kota Sikhar,Samaria" },
  { nomor: 279, soal: "Siapakah yang dikenal sebagai nabi yang meratap?", jawaban: "Yeremia" },
  { nomor: 280, soal: "Apa yang dibawa Nikodemus ketika datang kepada Yesus?", jawaban: "Campuran minyak mur dan minyak gaharu" },
  { nomor: 281, soal: "Siapakah nabi PL yang diperintahkan menikah dengan seorang pelacur?", jawaban: "Hosea" },
  { nomor: 282, soal: "Siapakah dua gembala jemaat penerima surat Paulus?", jawaban: "Timotius dan Titus" },
  { nomor: 283, soal: "Siapakah orang yang menderita hebat tetapi tetap percaya kepada Allah?", jawaban: "Ayub" },
  { nomor: 284, soal: "Siapakah nama ayah Abraham?", jawaban: "Terah" },
  { nomor: 285, soal: "Kata apakah dalam PB yang berarti diurapi oleh Tuhan?", jawaban: "Kristus" },
  { nomor: 286, soal: "Siapakah dua orang yang berjalan di atas air?", jawaban: "Yesus dan Petrus" },
  { nomor: 287, soal: "Sebutkan dua kitab PL yang memakai nama perempuan!", jawaban: "Ester dan Rut" },
  { nomor: 288, soal: "Ke manakah dua bangsa umat Allah dibuang?", jawaban: "Israel ke Asyur dan Yehuda ke Babel" },
  { nomor: 289, soal: "Siapakah raja paling berhikmat di dunia?", jawaban: "Salomo" },
  { nomor: 290, soal: "Surat apakah yang dikenal sebagai surat sukacita?", jawaban: "Filipi" },
  { nomor: 291, soal: "Di manakah terdapat Doa Bapa Kami?", jawaban: "Matius 6:9–13" },
  { nomor: 292, soal: "Apa bunyi Yohanes 15:1?", jawaban: "Akulah pokok anggur yang benar dan Bapa-Kulah pengusahanya" },
  { nomor: 293, soal: "Apa bunyi Yohanes 14:6?", jawaban: "Akulah jalan dan kebenaran dan hidup,tidak ada seorang pun yang datang kepada Bapa kalau tidak melalui Aku" },
  { nomor: 294, soal: "Berapa lama kegelapan terjadi saat Yesus disalibkan?", jawaban: "Tiga jam,dari jam 12siang sampai jam 3 sore" },
  { nomor: 295, soal: "Mukjizat apa saja yang terjadi saat Yesus wafat?", jawaban: "Kegelapan,tabir Bait Suci terbelah,gempa bumi,kubur terbuka,orang kudus bangkit" },
  { nomor: 296, soal: "Siapakah nama istri Ishak?", jawaban: "Ribka" },
  { nomor: 297, soal: "Pada usia berapakah Abraham meninggal?", jawaban: "175tahun" },
  { nomor: 298, soal: "Siapakah anak-anak Yusuf yang lahir di Mesir?", jawaban: "Manasye dan Efraim" },
  { nomor: 299, soal: "Berapa usia Yusuf saat meninggal?", jawaban: "110tahun" },
  { nomor: 300, soal: "Kota apa yang dibangun Israel untuk Firaun saat diperbudak?", jawaban: "Pitom dan Raamses" },
  { nomor: 301, soal: "Dari suku manakah Musa berasal?", jawaban: "Lewi" },
  { nomor: 302, soal: "Dalam bentuk apakah Allah pertama kali menampakkan diri kepada Musa?", jawaban: "Api" },
  { nomor: 303, soal: "Kitab Keluaran terdiri dari berapa pasal?", jawaban: "40pasal" },
  { nomor: 304, soal: "Perayaan Paskah PL diperingati sebagai apa?", jawaban: "Hari keluarnya Israel dari Mesir" },
  { nomor: 305, soal: "Saat siang hari Tuhan menuntun Israel dengan apa?", jawaban: "Tiang awan" },
  { nomor: 306, soal: "Siapakah nama mertua Musa?", jawaban: "Yitro" },
  { nomor: 307, soal: "Di gunung apakah Tuhan memberi hukum kepada Musa?", jawaban: "Gunung Sinai" },
  { nomor: 308, soal: "Di manakah Yesus pertama kali dicobai?", jawaban: "Padang gurun" },
  { nomor: 309, soal: "Penyakit apakah yang diderita mertua Petrus?", jawaban: "Demam" },
  { nomor: 310, soal: "Injil Markus terdiri dari berapa pasal?", jawaban: "16pasal" },
  { nomor: 311, soal: "Pakaian apakah yang dikenakan Yohanes Pembaptis?", jawaban: "Bulu unta" },
  { nomor: 312, soal: "Bagaimana cara Yohanes Pembaptis dibunuh?", jawaban: "Dipenggal kepalanya" },
  { nomor: 313, soal: "Siapakah nama ayah Yohanes Pembaptis?", jawaban: "Zakharia" },
  { nomor: 314, soal: "Melalui siapakah Allah memberitakan kelahiran Yesus kepada Maria?", jawaban: "Malaikat Gabriel" },
  { nomor: 315, soal: "Injil Lukas terdiri dari berapa pasal?", jawaban: "24pasal" },
  { nomor: 316, soal: "Dengan siapa Yesus berbicara saat dimuliakan di atas gunung?", jawaban: "Musa dan Elia" },
  { nomor: 317, soal: "Pada zaman kaisar siapakah Yesus lahir?", jawaban: "Kaisar Agustus" },
  { nomor: 318, soal: "Di manakah nyanyian pujian Zakharia tertulis?", jawaban: "Lukas 1:67–80" },
  { nomor: 319, soal: "Berapa lama Maria tinggal di rumah Elisabet?", jawaban: "Tiga bulan" },
  { nomor: 320, soal: "Injil Yohanes terdiri dari berapa pasal?", jawaban: "21pasal" },
  { nomor: 321, soal: "Siapakah yang dibangkitkan Yesus di kampung Maria dan Marta?", jawaban: "Lazarus" },
  { nomor: 322, soal: "Kisah Para Rasul terdiri dari berapa pasal?", jawaban: "28pasal" },
  { nomor: 323, soal: "Mengapa orang yang lemah lembut berbahagia?", jawaban: "Mereka akan memiliki bumi" },
  { nomor: 324, soal: "Apakah pelita tubuh menurut Lukas 11:34?", jawaban: "Mata" },
  { nomor: 325, soal: "Siapakah gembala pertama dalam Alkitab?", jawaban: "Habel" },
  { nomor: 326, soal: "Siapakah orang Ibrani yang menjadi penguasa di Mesir?", jawaban: "Yusuf" },
  { nomor: 327, soal: "Binatang apakah satu-satunya yang dikutuk Tuhan?", jawaban: "Ular" },
  { nomor: 328, soal: "Siapakah yang mengutuk pohon ara karena tidak berbuah?", jawaban: "Yesus" },
  { nomor: 329, soal: "Siapakah dua bidan Ibrani yang menentang perintah Firaun?", jawaban: "Pua dan Sifra" },
  { nomor: 330, soal: "Siapakah raja Israel yang pertama?", jawaban: "Saul" },
  { nomor: 331, soal: "Siapakah hakim Israel yang pertama?", jawaban: "Otniel" },
  { nomor: 332, soal: "Siapakah yang pertama menemukan bayi Musa di sungai?", jawaban: "Putri Firaun" },
  { nomor: 333, soal: "Siapakah rasul yang dibuang ke Pulau Patmos?", jawaban: "Yohanes" },
  { nomor: 334, soal: "Siapakah penulis Kitab Mazmur?", jawaban: "Daud" },
  { nomor: 335, soal: "Nama apakah yang diberikan Abraham kepada Sarai?", jawaban: "Sara" },
  { nomor: 336, soal: "Siapakah ratu yang digantikan oleh Ester?", jawaban: "Ratu Wasti" },
  { nomor: 337, soal: "Berapa lama bangsa Israel tinggal di Mesir?", jawaban: "430tahun" },
  { nomor: 338, soal: "Apakah tanda perjanjian Allah dengan Nuh?", jawaban: "Pelangi" },
  { nomor: 339, soal: "Siapakah hakim yang bertangan kidal?", jawaban: "Ehud" },
  { nomor: 340, soal: "Siapakah raja yang dibunuh oleh Ehud?", jawaban: "Raja Eglon" },
  { nomor: 341, soal: "Siapakah yang mati jatuh dari jendela saat mendengarkan khotbah?", jawaban: "Eutikhus" },
  { nomor: 342, soal: "Siapakah yang membangkitkan Eutikhus?", jawaban: "Paulus" },
  { nomor: 343, soal: "Kebun anggur milik siapa yang direbut dengan fitnah?", jawaban: "Nabot" },
  { nomor: 344, soal: "Siapakah raja yang membunuh Nabot?", jawaban: "Raja Ahab" },
  { nomor: 345, soal: "Apakah pekerjaan Kain dan Habel?", jawaban: "Kain petani dan Habel gembala" },
  { nomor: 346, soal: "Berapa lama hujan turun pada zaman Nuh?", jawaban: "40hari 40malam" },
  { nomor: 347, soal: "Apa isi perjanjian Allah dengan Nuh?", jawaban: "Tidak akan ada lagi air bah memusnahkan bumi" },
  { nomor: 348, soal: "Apa tujuan pendirian Menara Babel?", jawaban: "Mencari nama agar tidak terserak" },
  { nomor: 349, soal: "Siapakah imam yang memberkati Abraham?", jawaban: "Melkisedek" },
  { nomor: 350, soal: "Siapakah anak Abraham dari Sara dan Hagar?", jawaban: "Ishak dan Ismail" },
  { nomor: 351, soal: "Kota apa yang dimusnahkan dengan api dan belerang?", jawaban: "Sodom dan Gomora" },
  { nomor: 352, soal: "Pada usia berapakah Sara meninggal?", jawaban: "127tahun" },
  { nomor: 353, soal: "Siapakah anak-anak Ishak?", jawaban: "Esau dan Yakub" },
  { nomor: 354, soal: "Dengan apa Esau menjual hak kesulungannya?", jawaban: "Roti dan masakan kacang merah" },
  { nomor: 355, soal: "Ke mana Yakub melarikan diri setelah menipu?", jawaban: "Padan-Aram" },
  { nomor: 356, soal: "Apa nama lain Betel?", jawaban: "Kota Lus" },
  { nomor: 357, soal: "Siapakah istri-istri Yakub?", jawaban: "Rahel dan Lea" },
  { nomor: 358, soal: "Apa arti Pniel?", jawaban: "Tempat Yakub melihat Allah berhadapan muka" },
  { nomor: 359, soal: "Apa dua mimpi Yusuf?", jawaban: "Berkas gandum sujud dan matahari bulan sebelas bintang sujud" },
  { nomor: 360, soal: "Istri siapakah yang memfitnah Yusuf?", jawaban: "Istri Potifar" },
  { nomor: 361, soal: "Apa arti mimpi Firaun?", jawaban: "Tujuh tahun kelimpahan dan tujuh tahun kelaparan" },
  { nomor: 362, soal: "Nama lain apakah yang diberikan Firaun kepada Yusuf?", jawaban: "Zafnat-Paaneah" },
  { nomor: 363, soal: "Siapakah istri Yusuf?", jawaban: "Asnat" },
  { nomor: 364, soal: "Siapakah anak-anak Yusuf?", jawaban: "Manasye dan Efraim" },
  { nomor: 365, soal: "Apa pekerjaan Musa sebelum dipanggil Tuhan?", jawaban: "Gembala domba" },
  { nomor: 366, soal: "Di gunung apakah Allah mengutus Musa?", jawaban: "Gunung Horeb" },
  { nomor: 367, soal: "Laut apakah yang dibelah Tuhan?", jawaban: "Laut Teberau" },
  { nomor: 368, soal: "Di mana terdapat 12mata air dan 70pohon korma?", jawaban: "Elim" },
  { nomor: 369, soal: "Apa nama roti di padang gurun?", jawaban: "Manna" },
  { nomor: 370, soal: "Apa nama daging yang dimakan Israel di padang gurun?", jawaban: "Burung puyuh" },
  { nomor: 371, soal: "Di mana Israel mencobai Tuhan?", jawaban: "Masa dan Meriba" },
  { nomor: 372, soal: "Siapakah mertua Musa?", jawaban: "Yitro" },
  { nomor: 373, soal: "Apa yang dibuat Israel dan Harun saat Musa di Sinai?", jawaban: "Anak lembu emas" },
  { nomor: 374, soal: "Siapakah yang dipilih Tuhan membangun Kemah Suci?", jawaban: "Bezaleel dan Aholiab" },
  { nomor: 375, soal: "Siapakah nama ayah dan ibu Yesus?", jawaban: "Ibu Maria dan ayah Yusuf" },
  { nomor: 376, soal: "Persembahan apa yang dibawa orang Majus dari timur?", jawaban: "Emas,kemenyan,dan mur" },
  { nomor: 377, soal: "Apa pakaian dan makanan Yohanes Pembaptis?", jawaban: "Jubah bulu unta,ikat pinggang kulit,belalan dan madu hutan" },
  { nomor: 378, soal: "Peristiwa apa yang terjadi setelah Yesus dibaptis?", jawaban: "Langit terbuka,Roh Kudus turun seperti merpati,dan suara Bapa dari surga" },
  { nomor: 379, soal: "Berapa lama Yesus berpuasa di padang gurun?", jawaban: "40hari 40malam" },
  { nomor: 380, soal: "Apa yang ditunggangi Yesus saat dielu-elukan di Yerusalem?", jawaban: "Keledai" },
  { nomor: 381, soal: "Apa yang dikenakan di kepala Yesus saat disalibkan?", jawaban: "Mahkota duri" },
  { nomor: 382, soal: "Ibu siapa yang disembuhkan Yesus dari demam?", jawaban: "Ibu mertua Simon Petrus" },
  { nomor: 383, soal: "Siapakah pemungut cukai yang mengikuti Yesus?", jawaban: "Lewi anak Alfeus" },
  { nomor: 384, soal: "Sisa berapa bakul setelah Yesus memberi makan 5000orang?", jawaban: "12bakul" },
  { nomor: 385, soal: "Apa jawaban Petrus saat Yesus bertanya \"Siapakah Aku ini\"?", jawaban: "Engkau adalah Mesias" },
  { nomor: 386, soal: "Apa yang dilakukan Yesus terhadap pedagang di Bait Allah?", jawaban: "Mengusir mereka dan membalikkan meja" },
  { nomor: 387, soal: "Berapa persembahan janda miskin?", jawaban: "Dua peser" },
  { nomor: 388, soal: "Siapakah orang tua Yohanes Pembaptis?", jawaban: "Zakharia dan Elisabet" },
  { nomor: 389, soal: "Siapakah orang bertubuh pendek yang ingin melihat Yesus?", jawaban: "Zakheus" },
  { nomor: 390, soal: "Kepada siapa Yesus berkata tentang lahir dari air dan Roh?", jawaban: "Nikodemus" },
  { nomor: 391, soal: "Siapakah yang bercakap-cakap dengan Yesus di tepi sumur?", jawaban: "Perempuan Samaria" },
  { nomor: 392, soal: "Apa kata Tomas sebelum percaya Yesus bangkit?", jawaban: "Ia tidak akan percaya sebelum melihat bekas paku" },
  { nomor: 393, soal: "Kepada siapa Yesus berkata \"Gembalakanlah domba-domba-Ku\"?", jawaban: "Simon Petrus" },
  { nomor: 394, soal: "Apa arti Matius?", jawaban: "Pemberian Allah" },
  { nomor: 395, soal: "Kitab Matius terdiri dari berapa pasal dan ayat?", jawaban: "28pasal dan 1072ayat" },
  { nomor: 396, soal: "Siapakah yang membawa Yesus ke padang gurun untuk dicobai?", jawaban: "Roh Kudus" },
  { nomor: 397, soal: "Apa jawaban Yesus tentang batu menjadi roti?", jawaban: "Manusia hidup bukan dari roti saja" },
  { nomor: 398, soal: "Apa jawaban Yesus tentang menjatuhkan diri dari bubungan?", jawaban: "Jangan mencobai Tuhan Allahmu" },
  { nomor: 399, soal: "Apa jawaban Yesus tentang menyembah iblis?", jawaban: "Engkau harus menyembah Tuhan Allahmu" },
  { nomor: 400, soal: "Ke mana Yesus menyingkir setelah Yohanes ditangkap?", jawaban: "Kapernaum" },
  { nomor: 401, soal: "Siapakah dua bersaudara yang dipanggil Yesus di danau Galilea?", jawaban: "Simon Petrus dan Andreas" },
  { nomor: 402, soal: "Yesus memanggil mereka menjadi apa?", jawaban: "Penjala manusia" },
  { nomor: 403, soal: "Apa yang Yesus lakukan saat berkeliling di Galilea?", jawaban: "Mengajar,memberitakan Injil,dan menyembuhkan" },
  { nomor: 404, soal: "Apa isi ucapan bahagia?", jawaban: "Berbahagia orang miskin,berdukacita,lemah lembut,lapar akan kebenaran,murah hati,suci hati,pembawa damai,dianiaya,dicela karena Kristus" },
  { nomor: 405, soal: "Di mana terdapat ajaran garam dan terang dunia?", jawaban: "Matius 5:13–16" },
  { nomor: 406, soal: "Mengapa terang harus bercahaya?", jawaban: "Supaya orang memuliakan Bapa di sorga" },
  { nomor: 407, soal: "Di mana Doa Bapa Kami tertulis?", jawaban: "Matius 6:9–13" },
  { nomor: 408, soal: "Siapakah yang pertama disembuhkan Yesus?", jawaban: "Orang sakit kusta" },
  { nomor: 409, soal: "Siapakah yang percaya hambanya sembuh oleh sabda Yesus?", jawaban: "Perwira di Kapernaum" },
  { nomor: 410, soal: "Yesus datang bukan memanggil orang benar melainkan siapa?", jawaban: "Orang berdosa" },
  { nomor: 411, soal: "Siapakah yang menjamah jumbai jubah Yesus?", jawaban: "Perempuan pendarahan 12tahun" },
  { nomor: 412, soal: "Siapakah yang berseru \"Kasihanilah kami hai Anak Daud\"?", jawaban: "Dua orang buta" },
  { nomor: 413, soal: "Apa akibat tidak memikul salib dan mengikut Yesus?", jawaban: "Tidak layak bagi Yesus" },
  { nomor: 414, soal: "Kota apa yang dikecam Yesus karena tidak bertobat?", jawaban: "Khorazim,Betsaida,Kapernaum" },
  { nomor: 415, soal: "Apa arti benih di pinggir jalan?", jawaban: "Firman dirampas oleh si jahat" },
  { nomor: 416, soal: "Apa arti benih di tanah berbatu?", jawaban: "Iman tidak berakar dan murtad" },
  { nomor: 417, soal: "Apa arti benih di semak duri?", jawaban: "Firman terhimpit kekhawatiran dan kekayaan" },
  { nomor: 418, soal: "Apa arti benih di tanah baik?", jawaban: "Berbuah 30,60,dan 100kali lipat" },
  { nomor: 419, soal: "Sisa berapa bakul saat memberi makan 5000orang?", jawaban: "12bakul" },
  { nomor: 420, soal: "Sisa berapa bakul saat memberi makan 4000orang?", jawaban: "7bakul" },
  { nomor: 421, soal: "Siapakah murid yang diberi kunci Kerajaan Sorga?", jawaban: "Petrus" },
  { nomor: 422, soal: "Mengapa murid harus menyangkal diri?", jawaban: "Supaya memperoleh hidup sejati" },
  { nomor: 423, soal: "Siapa yang ikut Yesus ke gunung transfigurasi?", jawaban: "Petrus,Yakobus,dan Yohanes" },
  { nomor: 424, soal: "Apa yang membuat murid ketakutan di gunung?", jawaban: "Suara Allah dari awan terang" },
  { nomor: 425, soal: "Apa yang dapat dilakukan dengan iman sebesar biji sesawi?", jawaban: "Memindahkan gunung" },
  { nomor: 426, soal: "Bagaimana syarat masuk Kerajaan Sorga?", jawaban: "Bertobat dan menjadi seperti anak kecil" },
  { nomor: 427, soal: "Mengapa jangan merendahkan anak kecil?", jawaban: "Malaikat mereka memandang wajah Bapa" },
  { nomor: 428, soal: "Berapa kali harus mengampuni?", jawaban: "70kali 7" },
  { nomor: 429, soal: "Kerajaan sorga seumpama raja yang mengadakan apa?", jawaban: "Perhitungan dengan hamba" },
  { nomor: 430, soal: "Apa hukum yang terutama?", jawaban: "Mengasihi Tuhan Allah" },
  { nomor: 431, soal: "Apa hukum yang kedua?", jawaban: "Mengasihi sesama" },
  { nomor: 432, soal: "Berapa jumlah gadis bijaksana dan bodoh?", jawaban: "Lima bijaksana dan lima bodoh" },
  { nomor: 433, soal: "Mengapa gadis bodoh disebut bodoh?", jawaban: "Tidak membawa minyak" },
  { nomor: 434, soal: "Apa yang dilakukan hamba 5talenta?", jawaban: "Menghasilkan 5talenta" },
  { nomor: 435, soal: "Apa yang dilakukan hamba 2talenta?", jawaban: "Menghasilkan 2talenta" },
  { nomor: 436, soal: "Apa yang dilakukan hamba 1talenta?", jawaban: "Menyembunyikan uang dan dihukum" },
  { nomor: 437, soal: "Di mana Yesus menubuatkan Petrus menyangkal-Nya?", jawaban: "Bukit Zaitun" },
  { nomor: 438, soal: "Dengan siapa Yesus ke Getsemani?", jawaban: "Petrus,Yakobus,dan Yohanes" },
  { nomor: 439, soal: "Apa doa pertama Yesus di Getsemani?", jawaban: "Biarlah kehendak-Mu yang jadi" },
  { nomor: 440, soal: "Apa teguran Yesus kepada murid yang tidur?", jawaban: "Berjaga dan berdoalah" },
  { nomor: 441, soal: "Dalam keadaan apa murid ditemukan Yesus?", jawaban: "Tertidur" },
  { nomor: 442, soal: "Kepada siapa Yesus dibawa setelah ditangkap?", jawaban: "Kayafas" },
  { nomor: 443, soal: "Siapakah yang mengoyakkan pakaian dan berkata Yesus menghujat?", jawaban: "Kayafas" },
  { nomor: 444, soal: "Setelah Kayafas Yesus dibawa ke siapa?", jawaban: "Pilatus" },
  { nomor: 445, soal: "Apa kata Pilatus saat membasuh tangan?", jawaban: "Aku tidak bersalah" },
  { nomor: 446, soal: "Apa jawaban rakyat?", jawaban: "Biarlah darah-Nya atas kami" },
  { nomor: 447, soal: "Siapakah yang membantu memikul salib Yesus?", jawaban: "Simon dari Kirene" },
  { nomor: 448, soal: "Yesus diberi minum apa di salib?", jawaban: "Anggur bercampur empedu" },
  { nomor: 449, soal: "Siapakah perempuan yang melihat dari jauh?", jawaban: "Maria Magdalena dan Maria lainnya" },
  { nomor: 450, soal: "Dengan kain apa Yesus dikafani?", jawaban: "Kain lenan putih" },
  { nomor: 451, soal: "Siapakah yang tinggal di depan kubur Yesus?", jawaban: "Maria Magdalena dan Maria yang lain" },
  { nomor: 452, soal: "Siapakah yang datang ke kubur saat fajar?", jawaban: "Maria Magdalena dan Maria yang lain" },
  { nomor: 453, soal: "Siapakah yang menggulingkan batu kubur?", jawaban: "Malaikat Tuhan" },
  { nomor: 454, soal: "Di mana Yesus pertama kali menampakkan diri kepada murid?", jawaban: "Galilea" },
  { nomor: 455, soal: "Apa perkataan Yesus setelah kebangkitan?", jawaban: "Kepada-Ku diberikan segala kuasa" },
  { nomor: 456, soal: "Apa arti Akeldama?", jawaban: "Tanah Darah" },
  { nomor: 457, soal: "Pengajar dan penafsir Taurat disebut apa?", jawaban: "Ahli Taurat" },
  { nomor: 458, soal: "Nama iblis sebagai kepala roh jahat?", jawaban: "Beelzebul" },
  { nomor: 459, soal: "Simbol lambang penderitaan manusia?", jawaban: "Cawan" },
  { nomor: 460, soal: "Golongan Yahudi yang taat Taurat dan adat?", jawaban: "Farisi" },
  { nomor: 461, soal: "Bahasa Ibrani puji Tuhan?", jawaban: "Haleluya" },
  { nomor: 462, soal: "Perayaan pembebasan Israel dari Mesir disebut?", jawaban: "Paskah" },
  { nomor: 463, soal: "Perayaan roti tanpa ragi disebut?", jawaban: "Hari Raya Roti Tidak Beragi" },
  { nomor: 464, soal: "Golongan pendukung Herodes disebut?", jawaban: "Herodian" },
  { nomor: 465, soal: "Golongan utama dalam Mahkamah Agama?", jawaban: "Imam-imam kepala" },
  { nomor: 466, soal: "Apa arti Eklesia?", jawaban: "Perkumpulan orang yang dipanggil Allah" },
  { nomor: 467, soal: "Apa arti Mesias?", jawaban: "Yang diurapi" },
  { nomor: 468, soal: "Mengapa Yesus disebut Kristus?", jawaban: "Karena dipilih Allah sebagai Juruselamat" },
  { nomor: 469, soal: "Badan keagamaan Yahudi tertinggi disebut?", jawaban: "Mahkamah Agama" },
  { nomor: 470, soal: "Siapa saja anggota Mahkamah Agama?", jawaban: "Imam kepala,ahli Taurat,dan tua-tua" },
  { nomor: 471, soal: "Kota asal Yesus di Galilea?", jawaban: "Nazaret" },
  { nomor: 472, soal: "Cerita untuk menjelaskan hal rohani disebut?", jawaban: "Perumpamaan" },
  { nomor: 473, soal: "Siapakah gubernur Romawi Yudea tahun 26–36M?", jawaban: "Pontius Pilatus" },
  { nomor: 474, soal: "Ukuran timbangan 3000syikal disebut?", jawaban: "Talenta" },
  { nomor: 475, soal: "Apa arti Lukas?", jawaban: "Orang yang dilahirkan pada waktu fajar" },
  { nomor: 476, soal: "Siapakah pasangan suami istri pada zaman Herodes raja Yudea yang hidup benar di hadapan Allah?", jawaban: "Zakaria dari rombongan Abia dan istrinya Elisabet dari keturunan Harun" },
  { nomor: 477, soal: "Siapakah yang akan menjadi besar di hadapan Tuhan dan penuh Roh Kudus sejak dalam kandungan?", jawaban: "Yohanes" },
  { nomor: 478, soal: "Siapakah yang berjalan mendahului Tuhan dalam Roh dan kuasa Elia?", jawaban: "Yohanes" },
  { nomor: 479, soal: "Siapa nama malaikat yang diutus Allah kepada Zakaria?", jawaban: "Gabriel" },
  { nomor: 480, soal: "Apakah Zakaria percaya berita malaikat?", jawaban: "Tidak,sehingga ia menjadi bisu" },
  { nomor: 481, soal: "Berapa lama Elisabet tidak menampakkan diri setelah mengandung?", jawaban: "Lima bulan" },
  { nomor: 482, soal: "Pada bulan keenam malaikat Gabriel diutus ke kota apa?", jawaban: "Nazaret" },
  { nomor: 483, soal: "Apa nama bulan keenam?", jawaban: "Elul" },
  { nomor: 484, soal: "Kapan anak dalam rahim Elisabet melonjak kegirangan?", jawaban: "Saat Elisabet mendengar salam Maria" },
  { nomor: 485, soal: "Siapa yang membantah pemberian nama Zakaria kepada Yohanes?", jawaban: "Elisabet" },
  { nomor: 486, soal: "Kapan mulut Zakaria terbuka kembali?", jawaban: "Saat ia menulis nama Yohanes" },
  { nomor: 487, soal: "Sampai kapan Yohanes tinggal di padang gurun?", jawaban: "Sampai ia menampakkan diri kepada Israel" },
  { nomor: 488, soal: "Perahu siapakah yang dinaiki Yesus di Danau Genesaret?", jawaban: "Perahu Simon" },
  { nomor: 489, soal: "Apa perintah Yesus kepada Simon di perahunya?", jawaban: "Menolakkan perahu sedikit jauh dari pantai" },
  { nomor: 490, soal: "Apa ungkapan Yesus kepada orang lumpuh?", jawaban: "Bangunlah,angkatlah tempat tidurmu dan pulangl" },
  { nomor: 491, soal: "Di Lukas berapa Yesus memanggil dua belas murid?", jawaban: "Lukas 6:12–16" },
  { nomor: 492, soal: "Di kota manakah Yesus membangkitkan anak muda seorang janda?", jawaban: "Nain" },
  { nomor: 493, soal: "Apa yang Yesus berikan kepada dua belas murid sebelum diutus?", jawaban: "Kuasa dan tenaga menyembuhkan penyakit serta menguasai setan" },
  { nomor: 494, soal: "Berapa hari sesudah pengajaran Yesus membawa Petrus,Yakobus,dan Yohanes ke gunung?", jawaban: "Delapan hari" },
  { nomor: 495, soal: "Berapa jumlah murid yang diutus berdua-dua?", jawaban: "Tujuh puluh murid" },
  { nomor: 496, soal: "Sebutkan empat kota yang dikecam Yesus?", jawaban: "Khorazim,Betsaida,Tirus,dan Sidon" },
  { nomor: 497, soal: "Mengapa Yesus berkata bersukacitalah kepada 70murid?", jawaban: "Karena nama mereka terdaftar di sorga" },
  { nomor: 498, soal: "Siapakah yang tergerak hatinya melihat orang dirampok?", jawaban: "Orang Samaria yang baik hati" },
  { nomor: 499, soal: "Siapakah yang duduk dekat kaki Tuhan dan mendengar Firman?", jawaban: "Maria" },
  { nomor: 500, soal: "Siapa kepala pemungut cukai kaya di Yerikho?", jawaban: "Zakheus" },
  { nomor: 501, soal: "Apa arti ragi dalam ajaran Yesus?", jawaban: "Kemunafikan orang Farisi" },
  { nomor: 502, soal: "Dari sepuluh orang kusta siapa yang kembali bersyukur?", jawaban: "Orang Samaria" },
  { nomor: 503, soal: "Mengapa orang membawa anak-anak kecil kepada Yesus?", jawaban: "Supaya Yesus menjamah mereka" },
  { nomor: 504, soal: "Dimanakah Yesus menyelamatkan Zakheus?", jawaban: "Di rumah Zakheus" },
  { nomor: 505, soal: "Apa komitmen Zakheus kepada Yesus?", jawaban: "Memberi setengah harta kepada orang miskin dan mengganti empat kali lipat" },
  { nomor: 506, soal: "Dalam perumpamaan mina ada berapa hamba?", jawaban: "Sepuluh hamba" },
  { nomor: 507, soal: "Berapa mina hamba pertama dan hasilnya?", jawaban: "Sepuluh mina menghasilkan sepuluh mina" },
  { nomor: 508, soal: "Berapa mina hamba kedua dan hasilnya?", jawaban: "Lima mina menghasilkan lima mina" },
  { nomor: 509, soal: "Berapa mina hamba ketiga dan hasilnya?", jawaban: "Satu mina tidak menghasilkan apa-apa" },
  { nomor: 510, soal: "Mengapa hamba ketiga tidak berbuah?", jawaban: "Karena minanya disimpan dalam sapu tangan" },
  { nomor: 511, soal: "Apa yang terjadi dengan mina hamba ketiga?", jawaban: "Diambil dan diberikan kepada yang beroleh sepuluh mina" },
  { nomor: 512, soal: "Apa kata Yesus saat memecahkan roti?", jawaban: "Inilah tubuh-Ku yang diserahkan bagi kamu" },
  { nomor: 513, soal: "Sampai kapan Yesus tidak minum hasil pokok anggur?", jawaban: "Sampai Kerajaan Allah datang" },
  { nomor: 514, soal: "Untuk apa Yesus berdoa bagi Simon?", jawaban: "Supaya imannya jangan gugur dan menguatkan saudarasaudaranya" },
  { nomor: 515, soal: "Apa kata Yesus saat Yudas mencium-Nya?", jawaban: "Engkau menyerahkan Anak Manusia dengan ciuman" },
  { nomor: 516, soal: "Mengapa Herodes girang melihat Yesus?", jawaban: "Karena sudah lama ingin melihat-Nya" },
  { nomor: 517, soal: "Apa ungkapan penjahat di salib yang sadar?", jawaban: "Yesus,ingatlah aku apabila Engkau datang sebagai Raja" },
  { nomor: 518, soal: "Apa jawaban Yesus kepada penjahat itu?", jawaban: "Hari ini engkau bersama Aku di Firdaus" },
  { nomor: 519, soal: "Apa perkataan terakhir Yesus?", jawaban: "Ya Bapa,ke dalam tangan-Mu Kuserahkan nyawa-Ku" },
  { nomor: 520, soal: "Di jalan apakah Yesus menampakkan diri setelah bangkit?", jawaban: "Jalan ke Emaus" },
  { nomor: 521, soal: "Apa yang membuat murid Emaus mengenal Yesus?", jawaban: "Saat Ia memecahkan roti" },
  { nomor: 522, soal: "Dimana Yesus terangkat ke sorga?", jawaban: "Betania" },
  { nomor: 523, soal: "Apa bunyi Yohanes 1:1?", jawaban: "Pada mulanya adalah Firman,Firman itu bersama-sama dengan Allah dan Firman itu adalah Allah" },
  { nomor: 524, soal: "Siapakah dua murid Yohanes yang pertama mengikut Yesus?", jawaban: "Andreas dan Simon Petrus" },
  { nomor: 525, soal: "Mujizat kedua Yesus di Kapernaum adalah?", jawaban: "Menyembuhkan anak pegawai istana" },
  { nomor: 526, soal: "Dimana kolam Bethesda terletak?", jawaban: "Di Yerusalem dekat Pintu Gerbang Domba" },
  { nomor: 527, soal: "Berapa serambi kolam Bethesda?", jawaban: "Lima serambi" },
  { nomor: 528, soal: "Sudah berapa lama orang sakit di Bethesda menderita?", jawaban: "Tiga puluh delapan tahun" },
  { nomor: 529, soal: "Apa nama hari raya orang Yahudi?", jawaban: "Hari Raya Pondok Daun" },
  { nomor: 530, soal: "Siapakah Imam Kepala yang membela Yesus?", jawaban: "Nikodemus" },
  { nomor: 531, soal: "Siapakah bapa segala dusta?", jawaban: "Iblis" },
  { nomor: 532, soal: "Dimana orang buta disuruh membasuh diri?", jawaban: "Kolam Siloam" },
  { nomor: 533, soal: "Apa arti Siloam?", jawaban: "Yang diutus" },
  { nomor: 534, soal: "Apa arti Yohanes 11:25tentang orang percaya?", jawaban: "Ia akan hidup walaupun sudah mati" },
  { nomor: 535, soal: "Kepada siapa Yesus pertama kali dihadapkan setelah ditangkap?", jawaban: "Hanas" },
  { nomor: 536, soal: "Setelah Hanas Yesus dibawa kepada siapa?", jawaban: "Kayafas" },
  { nomor: 537, soal: "Setelah Kayafas Yesus dibawa kemana?", jawaban: "Kepada Pilatus" },
  { nomor: 538, soal: "Apa arti Litostrotos?", jawaban: "Tempat duduk pengadilan" },
  { nomor: 539, soal: "Apa yang dibawa Nikodemus kepada Yesus?", jawaban: "Campuran mur dan gaharu sekitar lima puluh kati" },
  { nomor: 540, soal: "Siapa dua murid yang datang ke kubur lalu pulang?", jawaban: "Petrus dan Yohanes" },
  { nomor: 541, soal: "Apa perkataan Yesus saat mengembusi murid-murid?", jawaban: "Terimalah Roh Kudus" },
  { nomor: 542, soal: "Siapakah murid yang tidak percaya sebelum melihat bekas paku?", jawaban: "Tomas Didimus" },
  { nomor: 543, soal: "Siapa murid di Danau Tiberias saat Yesus menampakkan diri?", jawaban: "Petrus,Tomas,Natanael, Yakobus,Yohanes,dan dua murid lain" },
  { nomor: 544, soal: "Apa arti Zakharia?", jawaban: "Tuhan telah mengingat" },
  { nomor: 545, soal: "Siapakah ayah Zakharia nabi?", jawaban: "Berekhya bin Ido" },
  { nomor: 546, soal: "Kapan firman Tuhan datang kepada Zakharia pertama kali?", jawaban: "Bulan 8tahun kedua Raja Darius" },
  { nomor: 547, soal: "Kapan penglihatan-penglihatan Zakharia diterima?", jawaban: "Hari 24bulan 11tahun kedua Darius" },
  { nomor: 548, soal: "Pasal 1–8Zakharia berisi tentang apa?", jawaban: "Penglihatan-penglihatan" },
  { nomor: 549, soal: "Sebutkan delapan penglihatan Zakharia?", jawaban: "Penunggang kuda,empat tanduk,tali ukur,Imam Yosua,kandil emas,gulungan kitab,perempuan dalam gantang,empat kereta" },
  { nomor: 550, soal: "Kapan firman Tuhan tentang puasa datang?", jawaban: "Tahun keempat Raja Darius" },
  { nomor: 551, soal: "Siapakah bupati Yehuda zaman Darius?", jawaban: "Zerubabel" },
  { nomor: 552, soal: "Siapakah Imam Besar zaman Darius?", jawaban: "Yosua bin Yozadak" },
  { nomor: 553, soal: "Siapa yang pulang lebih dahulu dari Babel?", jawaban: "Heldai,Tobia,dan Yedaya" },
  { nomor: 554, soal: "Siapa utusan penduduk Betel?", jawaban: "Sarezer dan Regem-Melekh" },
  { nomor: 555, soal: "Kuda apa menarik empat kereta Zakharia?", jawaban: "Merah,hitam,putih,dan berbelang" },
  { nomor: 556, soal: "Apa dua tongkat gembala?", jawaban: "Tongkat kemurahan dan tongkat ikatan" },
  { nomor: 557, soal: "Berapa upah gembala?", jawaban: "Tiga puluh uang perak" },
  { nomor: 558, soal: "Apa simbol Yerusalem menjadi pasu?", jawaban: "Kekuasaan dan kedaulatan" },
  { nomor: 559, soal: "Kaum Yehuda menjadi seperti apa?", jawaban: "Anglo berapi dan suluh berapi" },
  { nomor: 560, soal: "Ratapan Yerusalem sebanding dengan apa?", jawaban: "Ratapan Hadad-Rimon" },
  { nomor: 561, soal: "Pada zaman siapa terjadi gempa besar?", jawaban: "Raja Uzia" },
  { nomor: 562, soal: "Tulah apa bagi bangsa yang menyerang Yerusalem?", jawaban: "Daging,mata,dan lidah menjadi busuk" },
  { nomor: 563, soal: "Tulah itu menimpa apa saja?", jawaban: "Kuda,bagal,unta,keledai,dan semua hewan" },
  { nomor: 564, soal: "Apa akibat tidak datang menyembah Tuhan?", jawaban: "Tidak turun hujan" },
  { nomor: 565, soal: "Berapa lama Yerusalem rusak?", jawaban: "Tujuh puluh tahun" },
  { nomor: 566, soal: "Mengapa Tuhan menurunkan air bah?", jawaban: "Karena kejahatan manusia besar" },
  { nomor: 567, soal: "Kemana Abram pergi sebelum berpisah dengan Lot?", jawaban: "Tanah Negeb" },
  { nomor: 568, soal: "Siapakah ayah Musa?", jawaban: "Amram" },
  { nomor: 569, soal: "Apa yang dimusnahkan oleh air bah?", jawaban: "Manusia dan semua makhluk hidup" },
  { nomor: 570, soal: "Dimana Abram tinggal sebelum Haran?", jawaban: "Ur-Kasdim" },
  { nomor: 571, soal: "Dimana Abraham mempersembahkan Ishak?", jawaban: "Gunung Moria" },
  { nomor: 572, soal: "Mengapa Abram dan Lot berpisah?", jawaban: "Supaya tidak terjadi perkelahian" },
  { nomor: 573, soal: "Apa alas kepala Yakub di Betel?", jawaban: "Batu" },
  { nomor: 574, soal: "Mengapa istri tuan Mesir menyukai Yusuf?", jawaban: "Karena Yusuf elok parasnya" },
  { nomor: 575, soal: "Siapakah ibu Musa?", jawaban: "Yokhebed" },
  { nomor: 576, soal: "Siapakah keluarga Abraham dekat Sodom?", jawaban: "Lot" },
  { nomor: 577, soal: "Berapa bujang ikut Abraham ke Moria?", jawaban: "Dua orang" },
  { nomor: 578, soal: "Apa yang Yakub lihat di Betel?", jawaban: "Tangga sampai ke sorga" },
  { nomor: 579, soal: "Berapa umur Yusuf menggembalakan domba?", jawaban: "Tujuh belas tahun" },
  { nomor: 580, soal: "Bangsa apa memperbudak Israel saat Musa lahir?", jawaban: "Mesir" },
  { nomor: 581, soal: "Siapa berkata darah adikmu berteriak?", jawaban: "Tuhan" },
  { nomor: 582, soal: "Kemana Yakub disuruh pergi?", jawaban: "Padang Aram ke Haran" },
  { nomor: 583, soal: "Dimana juru roti dan minuman dipenjara?", jawaban: "Rumah kepala pengawal" },
  { nomor: 584, soal: "Apa yang Yusuf lakukan saat memperkenalkan diri?", jawaban: "Menangis keras" },
  { nomor: 585, soal: "Siapa mengusulkan menjual Yusuf?", jawaban: "Yehuda" },
  { nomor: 586, soal: "Siapa berkata ini rumah Allah?", jawaban: "Yakub" },
  { nomor: 587, soal: "Apa arti nama Kain?", jawaban: "Saya menghasilkan" },
  { nmor: 588, soal: "Berapa hari Abraham ke Moria?", jawaban: "Tiga hari" },
  { nomor: 589, soal: "Apa perbedaan Esau dan Yakub?", jawaban: "Esau berbulu,Yakub licin" },
  { nomor: 590, soal: "Apa nama lama Betel?", jawaban: "Lus" },
  { nomor: 591, soal: "Nama baru Yakub dari Tuhan?", jawaban: "Israel" },
  { nomor: 592, soal: "Siapa kakak perempuan Musa?", jawaban: "Miryam" },
  { nomor: 593, soal: "Apa persembahan Kain?", jawaban: "Hasil tanah" },
  { nomor: 594, soal: "Dimana Terah menetap?", jawaban: "Haran" },
  { nomor: 595, soal: "Mengapa Lot memilih Lembah Yordan?", jawaban: "Banyak air" },
  { nomor: 596, soal: "Siapa menerima berkat Ishak?", jawaban: "Yakub" },
  { nomor: 597, sxl: "Berapa bagian nazar Yakub?", jawaban: "Sepersepuluh" },
  { nomor: 598, soal: "Siapa ibu saudara Yusuf dari gundik?", jawaban: "Bilha dan Zilpa" },
  { nomor: 599, soal: "Ayah dan ibu Musa dari suku apa?", jawaban: "Lewi" },
  { nomor: 600, soal: "Apa persembahan Habel?", jawaban: "Anak sulung kambing domba" },
  { nomor: 601, soal: "Berapa tingkat bahtera Nuh?", jawaban: "Tiga tingkat" },
  { nomor: 602, soal: "Berapa umur Terah saat meninggal?", jawaban: "Dua ratus lima puluh tahun" },
  { nomor: 603, soal: "Apa perlengkapan Abraham ke Moria?", jawaban: "Kayu,api,dan pisau" },
  { nomor: 604, soal: "Dimana Abram mendirikan mezbah?", jawaban: "Mamre dekat Hebron" },
  { nomor: 605, soal: "Bagaimana keadaan mata Ishak?", jawaban: "Kabur" },
  { nomor: 606, soal: "Apa kata Yakub setelah mimpi?", jawaban: "Tuhan ada di tempat ini" },
  { nomor: 607, soal: "Mengapa Yusuf dibenci saudara-saudaranya?", jawaban: "Karena jubah indah dan dikasihi ayahnya" },
  { nomor: 608, soal: "Berapa lama Musa disembunyikan?", jawaban: "Tiga bulan" },
  { nomor: 609, soal: "Siapa berkata mendapat anak dengan pertolongan Tuhan?", jawaban: "Hawa" },
  { nomor: 610, soal: "Siapa mengusulkan Yusuf ke sumur?", jawaban: "Ruben" },
  { nomor: 611, soal: "Mengapa Ishak salah mengenali Yakub?", jawaban: "Karena tangan Yakub berbulu" },
  { nomor: 612, soal: "Mengapa juru roti dan minuman bersusah hati?", jawaban: "Karena mimpi tidak ada penafsir" },
  { nomor: 613, soal: "Mengapa Yusuf dikasihi tuannya?", jawaban: "Karena Tuhan menyertainya" },
  { nomor: 614, soal: "Siapakah yang mengatakan \"Bangunlah,bawalah isterimu dan kedua anakmu yang ada di sini,supaya engkau jangan mati lenyap karena kedurjanaan kota ini\"?", jawaban: "Dua malaikat Tuhan (Kejadian 19:15)" },
  { nomor: 615, soal: "Apa arti Habel?", jawaban: "Kekosongan" },
  { nomor: 616, soal: "Apa yang terjadi saat Kain mempersembahkan korban persembahannya?", jawaban: "Korban persembahannya tidak diindahkan Tuhan (Kejadian 4:5)" },
  { nomor: 617, soal: "Dengan apa bahtera Nuh harus ditutup dari luar dan dari dalam?", jawaban: "Pakal (Kejadian 6:14)" },
  { nomor: 618, soal: "Dimanakah Terah meninggal?", jawaban: "Di Haran (Kejadian 11:32)" },
  { nomor: 619, soal: "Lembah apa yang dipilih Lot saat berpisah dengan Abram?", jawaban: "Lembah Yordan (Kejadian 13:11)" },
  { nomor: 620, soal: "Apa jawaban Abraham tentang korban bakaran kepada Ishak?", jawaban: "Allah yang akan menyediakan anak domba untuk korban bakaran (Kejadian 22:8)" },
  { nomor: 621, soal: "Apa yang diminta Ishak kepada Esau sebelum memberkati dia?", jawaban: "Berburu binatang dan mengolah makanan yang enak (Kejadian 27:3–4)" },
  { nomor: 622, soal: "Seperti apa keturunan Yakub diumpamakan Tuhan dalam mimpi?", jawaban: "Seperti debu tanah banyaknya (Kejadian 28:14)" },
  { nomor: 623, soal: "Mengapa Yakub lebih mengasihi Yusuf?", jawaban: "Karena Yusuf lahir pada masa tuanya (Kejadian 37:3)" },
  { nomor: 624, soal: "Peti Musa terbuat dari apa?", jawaban: "Peti pandan yang dipakal dengan gala-gala dan ter (Keluaran 2:3)" },
  { nomor: 625, soal: "Bagaimana keadaan hati Kain setelah persembahannya ditolak?", jawaban: "Sangat panas dan mukanya muram (Kejadian 4:5)" },
  { nomor: 626, soal: "Mengapa Nuh dipilih Tuhan membangun bahtera?", jawaban: "Karena Nuh benar,tidak bercela,dan hidup bergaul dengan Allah (Kejadian 6:9)" },
  { nomor: 627, soal: "Apa janji Tuhan kepada Abram saat keluar dari Haran?", jawaban: "Menjadi bangsa besar,diberkati,dan menjadi berkat (Kejadian 12:2)" },
  { nomor: 628, soal: "Bagaimana keadaan orang Sodom menurut Alkitab?", jawaban: "Sangat jahat dan berdosa terhadap Tuhan (Kejadian 13:13)" },
  { nomor: 629, soal: "Berapa kali malaikat Tuhan memanggil nama Abraham di Gunung Moria?", jawaban: "Dua kali (Kejadian 22:11)" },
  { nomor: 630, soal: "Tugu batu yang didirikan Yakub akan menjadi apa?", jawaban: "Rumah Allah (Kejadian 28:22)" },
  { nomor: 631, soal: "Apa mimpi pertama Yusuf?", jawaban: "Berkas gandum saudara-saudaranya sujud kepada berkas Yusuf (Kejadian 37:7)" },
  { nomor: 632, soal: "Berapa umur Abram saat berangkat dari Haran?", jawaban: "Tujuh puluh lima tahun (Kejadian 12:4)" },
  { nomor: 633, soal: "Dengan apa Sodom dan Gomora dihancurkan?", jawaban: "Hujan belerang dan api dari langit (Kejadian 19:24)" },
  { nomor: 634, soal: "Binatang apa pengganti Ishak sebagai korban?", jawaban: "Domba jantan (Kejadian 22:13)" },
  { nomor: 635, soal: "Apa perlengkapan berburu Esau?", jawaban: "Senjata,tabung panah,dan busur (Kejadian 27:3)" },
  { nomor: 636, soal: "Apa yang Yakub tuangkan di atas tugu batu?", jawaban: "Minyak (Kejadian 28:18)" },
  { nomor: 637, soal: "Bagaimana Tuhan menyertai Yusuf di penjara?", jawaban: "Membuat Yusuf dikasihi kepala penjara (Kejadian 39:21)" },
  { nomor: 638, soal: "Apa mimpi juru minuman Firaun?", jawaban: "Pohon anggur dengan tiga carang dan piala Firaun (Kejadian 40:9–11)" },
  { nomor: 639, soal: "Mengapa Ruben mengusulkan Yusuf dimasukkan ke sumur?", jawaban: "Supaya dapat menyelamatkannya kemudian (Kejadian 37:22)" },
  { nomor: 640, soal: "Siapakah yang berkata \"Aku akan menghapuskan manusia dari muka bumi\"?", jawaban: "Tuhan (Kejadian 6:7)" },
  { nomor: 641, soal: "Apa arti nama Abraham?", jawaban: "Bapak orang beriman" },
  { nomor: 642, soal: "Bagaimana Kain membunuh Habel?", jawaban: "Dengan memukulnya (Kejadian 4:8)" },
  { nomor: 643, soal: "Berapa pasang binatang masuk ke bahtera?", jawaban: "Satu pasang jantan dan betina (Kejadian 7:2)" },
  { nomor: 644, soal: "Siapakah ayah Lot?", jawaban: "Haran (Kejadian 11:31)" },
  { nomor: 645, soal: "Kapan malaikat tiba di Sodom menemui Lot?", jawaban: "Pada waktu petang (Kejadian 19:1)" },
  { nomor: 646, soal: "Apa nama tempat persembahan Ishak?", jawaban: "Tuhan Menyediakan (Kejadian 22:14)" },
  { nomor: 647, soal: "Pakaian siapa dipakai Yakub untuk menipu Ishak?", jawaban: "Pakaian Esau yang indah (Kejadian 27:15)" },
  { nomor: 648, soal: "Apa isi nazar Yakub di Betel?", jawaban: "Tuhan akan menjadi Allahku (Kejadian 28:20–21)" },
  { nomor: 649, soal: "Apa mimpi kedua Yusuf?", jawaban: "Matahari,bulan,dan sebelas bintang sujud kepadanya (Kejadian 37:9)" },
  { nomor: 650, soal: "Apa tujuan putri Firaun ke Sungai Nil?", jawaban: "Mandi (Kejadian 2:5)" },
  { nomor: 651, soal: "Dimana Kain menetap setelah membunuh Habel?", jawaban: "Tanah Nod di sebelah timur Eden (Kejadian 4:16)" },
  { nomor: 652, soal: "Siapa yang dibawa Abram keluar dari Haran?", jawaban: "Sarai,Lot,harta benda,dan budak-budaknya (Kejadian 12:5)" },
  { nomor: 653, soal: "Apa yang terjadi pada istri Lot yang menoleh ke belakang?", jawaban: "Menjadi tiang garam (Kejadian 19:26)" },
  { nomor: 654, soal: "Berapa anak kambing yang diolah Ribka untuk Ishak?", jawaban: "Dua anak kambing (Kejadian 27:9)" },
  { nomor: 655, soal: "Dimana keluarga Yakub tinggal di Mesir?", jawaban: "Tanah Gosyen (Kejadian 45:10)" },
  { nomor: 656, soal: "Apa sebutan Yakub untuk tempat Betel?", jawaban: "Pintu gerbang sorga (Kejadian 28:17)" },
  { nomor: 657, soal: "Kemana Yusuf dilemparkan oleh saudara-saudaranya?", jawaban: "Ke dalam sumur kosong (Kejadian 37:24)" },
  { nomor: 658, soal: "Berapa usia Musa saat ditemukan putri Firaun?", jawaban: "Tiga bulan (Keluaran 2:2)" },
  { nomor: 659, soal: "Berapa kali lipat pembalasan bagi pembunuh Kain?", jawaban: "Tujuh kali lipat (Kejadian 4:15)" },
  { nomor: 660, soal: "Berapa kali Yakub menipu Esau?", jawaban: "Dua kali (Kejadian 27:36)" },
  { nomor: 661, soal: "Berapa malaikat yang menolong Lot keluar dari Sodom?", jawaban: "Dua malaikat (Kejadian 19:15)" },
  { nomor: 662, soal: "Keturunan Abraham diumpamakan seperti apa?", jawaban: "Bintang di langit dan pasir di laut (Kejadian 22:17)" },
  { nomor: 663, soal: "Apa yang dipakai Yakub untuk menutupi kulitnya?", jawaban: "Kulit anak kambing (Kejadian 27:16)" },
  { nomor: 664, soal: "Kepada siapa Yusuf dijual?", jawaban: "Kafilah orang Ismael (Kejadian 37:25)" },
  { nomor: 665, soal: "Sungai apa di tepi tempat Firaun bermimpi?", jawaban: "Sungai Nil (Kejadian 41:1)" },
  { nomor: 666, soal: "Apa pemberian khusus Yusuf kepada Benyamin?", jawaban: "Tiga ratus uang perak dan lima potong pesalin (Kejadian 45:22)" },
  { nomor: 667, soal: "Berapa lama air bah menutupi bumi?", jawaban: "Seratus lima puluh hari" },
  { nomor: 668, soal: "Siapa yang berkata Allah menyediakan korban?", jawaban: "Abraham (Kejadian 22:8)" },
  { nomor: 669, soal: "Apa arti mimpi juru minuman menurut Yusuf?", jawaban: "Tiga hari dan dipulihkan jabatannya (Kejadian 40:12–13)" },
  { nomor: 670, soal: "Kemana Abram berangkat dari pegunungan Ai?", jawaban: "Tanah Negeb (Kejadian 12:9)" },
  { nomor: 671, soal: "Apa yang Tuhan lakukan agar Kain tidak dibunuh?", jawaban: "Memberi tanda pada Kain (Kejadian 4:15)" },
  { nomor: 672, soal: "Berapa lama setelah juru minuman bebas Firaun bermimpi?", jawaban: "Dua tahun (Kejadian 41:1)" },
  { nomor: 673, soal: "Berapa jumlah orang benar pertama yang Abraham ajukan?", jawaban: "Lima puluh orang (Kejadian 18:24)" },
  { nomor: 674, soal: "Apa yang dilakukan malaikat kepada orang Sodom?", jawaban: "Membutakan mata mereka (Kejadian 19:11)" },
  { nomor: 675, soal: "Dimana Abraham tinggal setelah dari Moria?", jawaban: "Bersyeba (Kejadian 22:19)" },
  { nomor: 676, soal: "Apa yang dilakukan saudara Yusuf setelah melemparkan dia ke sumur?", jawaban: "Duduk makan (Kejadian 37:25)" },
  { nomor: 677, soal: "Kemana saudagar membawa Yusuf?", jawaban: "Ke Mesir (Kejadian 37:25)" },
  { nomor: 678, soal: "Apa pelajaran dari kisah Kain dan Habel?", jawaban: "Tuhan itu pengampun" },
  { nomor: 679, soal: "Apa reaksi Esau saat berkatnya dirampas?", jawaban: "Meraung-raung dengan sangat keras (Kejadian 27:34)" },
  { nomor: 680, soal: "Apa kata Ishak saat meraba Yakub?", jawaban: "Suara Yakub,tangan Esau (Kejadian 27:22)" },
  { nomor: 681, soal: "Apa yang dilakukan saudara Yusuf pada jubahnya?", jawaban: "Dirobek dan dilumuri darah kambing (Kejadian 37:31)" },
  { nomor: 682, soal: "Berapa harga Yusuf dijual?", jawaban: "Dua puluh syikal perak (Kejadian 37:28)" },
  { nomor: 683, soal: "Apa hukuman Tuhan atas Kain?", jawaban: "Menjadi pengembara dan tanah tidak menghasilkan (Kejadian 4:12)" },
  { nomor: 684, soal: "Berapa kali Abraham memohon bagi Sodom?", jawaban: "Lima kali (Kejadian 18:22–33)" },
  { nomor: 685, soal: "Kapan Lot meninggalkan Sodom?", jawaban: "Saat fajar menyingsing (Kejadian 19:15)" },
  { nomor: 686, soal: "Barang apa dibawa kafilah pembeli Yusuf?", jawaban: "Damar,balsam,dan damar ladan (Kejadian 37:25)" },
  { nomor: 687, soal: "Siapa orang Mesir yang membeli Yusuf?", jawaban: "Potifar (Kejadian 39:1)" },
  { nomor: 688, soal: "Berapa bagian hasil Mesir dipungut Firaun?", jawaban: "Seperlima bagian (Kejadian 41:34)" },
  { nomor: 689, soal: "Apa pelajaran dari Yakub di Betel?", jawaban: "Tuhan itu Pelindung" },
  { nomor: 690, soal: "Berapa orang yang selamat dari Sodom?", jawaban: "Tiga orang (Kejadian 19:30)" },
  { nomor: 691, soal: "Ke kota mana Lot diperintahkan pergi?", jawaban: "Zoar (Kejadian 19:22–23)" },
  { nomor: 692, soal: "Bagian tubuh mana ditutupi Yakub dengan kulit kambing?", jawaban: "Tangan dan leher (Kejadian 27:16)" },
  { nomor: 693, soal: "Apa jabatan Potifar?", jawaban: "Kepala pengawal raja (Kejadian 39:1)" },
  { nomor: 694, soal: "Berkat apa yang diterima Yakub dari Ishak?", jawaban: "Embun langit,tanah subur,bangsa-bangsa takluk,dan berkat Allah (Kejadian 27:28–29)" },
  { nomor: 695, soal: "Berapa tahun kelaparan tersisa saat Yusuf memperkenalkan diri?", jawaban: "Lima tahun (Kejadian 45:11)" },
  { nomor: 696, soal: "Siapa yang berkata berkat Esau telah dirampas?", jawaban: "Ishak (Kejadian 27:35)" },
  { nomor: 697, soal: "Apa bekal Yusuf untuk ayahnya ke Mesir?", jawaban: "Keledai berisi hasil terbaik Mesir dan makanan (Kejadian 45:23)" },
  { nomor: 698, soal: "Apa mimpi kedua Firaun?", jawaban: "Tujuh bulir gandum gemuk dimakan tujuh bulir kurus (Kejadian 41:22–24)" },
  { nomor: 699, soal: "Apa arti nama Israel?", jawaban: "Allah bergumul" },
  { nomor: 700, soal: "Apa ucapan pertama Yusuf setelah mendengar mimpi Firaun?", jawaban: "Allah memberitahukan apa yang akan dilakukan-Nya (Kejadian 41:25)" },
  { nomor: 701, soal: "Siapa anak tertua Kain?", jawaban: "Henokh" },
  { nomor: 702, soal: "Anak Nuh mana disebut bapa Kanaan?", jawaban: "Ham" },
  { nomor: 703, soal: "Siapa menopang tangan Musa melawan Amalek?", jawaban: "Harun dan Hur (Keluaran 17:12)" },
  { nomor: 704, soal: "Siapa pelihat yang diminta Balak?", jawaban: "Bileam bin Beor" },
  { nomor: 705, soal: "Gedung Hutan Libanon adalah apa?", jawaban: "Istana Salomo (1Raja-raja 7:1–2)" },
  { nomor: 706, soal: "Ayat \"oleh bilur-bilurnya kita sembuh\"terdapat di mana?", jawaban: "Yesaya 53:5" },
  { nomor: 707, soal: "Sungai apa terbelah saat Israel menyeberang?", jawaban: "Sungai Yordan" },
  { nomor: 708, soal: "Nabi yang berjalan telanjang tiga tahun?", jawaban: "Yesaya" },
  { nomor: 709, soal: "Rehabeam adalah anak siapa?", jawaban: "Raja Salomo" },
  { nomor: 710, soal: "Siapa orang Horon yang mengolok Nehemia?", jawaban: "Sanbalat" },
  { nomor: 711, soal: "Siapa nabi yang botak?", jawaban: "Elisa (2Raja-raja 2:23)" },
  { nomor: 712, soal: "Apa nama Babel Daniel,Hananya,Misael,dan Azarya?", jawaban: "Beltsazar,Sadrakh,Mesakh,Abednego (Daniel 1:6–7)" },
  { nomor: 713, soal: "Alat tukar zaman Rut?", jawaban: "Kasut" },
  { nomor: 714, soal: "Apa yang dipakai Elisa menyehatkan air Yerikho?", jawaban: "Garam" },
  { nomor: 715, soal: "Siapakah nabi yang ditegur Tuhan agar tidak menyebut dirinya masih muda?", jawaban: "Nabi Yeremia" },
  { nomor: 716, soal: "Sebutkan nama hakim-hakim Israel!", jawaban: "Otniel bin Kenas,Ehud bin Gera,Samgar bin Anat,Debora dan Barak,Gideon bin Yoas,Abimelekh bin Yerubaal,Tola bin Pua bin Dodo,Yair,Yefta bin Gilead,Ebzan,Elon,Abdon bin Hilel,Simson,Eli,dan Samuel bin Elkana" },
  { nomor: 717, soal: "Apa alasan Laban memberikan Lea lebih dahulu kepada Yakub?", jawaban: "Tidak biasa mengawinkan adik lebih dahulu daripada kakaknya (Kejadian 29:26)" },
  { nomor: 718, soal: "Siapa yang pernah didatangi panglima bala tentara Tuhan?", jawaban: "Yosua" },
  { nomor: 719, soal: "Dimanakah tertulis \"Besi menajamkan besi,orang menajamkan sesamanya\"?", jawaban: "Amsal 27:17" },
  { nomor: 720, soal: "Siapakah nabi yang mendapat penglihatan kemuliaan Tuhan di tepi Sungai Kebar?", jawaban: "Nabi Yehezkiel" },
  { nomor: 721, soal: "Siapakah yang melakukan pertobatan massal dengan puasa manusia dan ternak?", jawaban: "Orang Niniwe" },
  { nomor: 722, soal: "Apa arti kiasan Ohola dan Oholiba?", jawaban: "Ohola adalah Samaria dan Oholiba adalah Yerusalem (Yehezkiel 23:4)" },
  { nomor: 723, soal: "Di kitab apakah tertulis \"Cinta kuat seperti maut\"?", jawaban: "Kidung Agung 8:6" },
  { nomor: 724, soal: "Siapakah tiga sahabat Ayub?", jawaban: "Elifas,Bildad,dan Zofar (Ayub 2:11)" },
  { nomor: 725, soal: "Raja manakah yang bertubuh sangat gendut?", jawaban: "Eglon,raja Moab (Hakim-hakim 3:17)" },
  { nomor: 726, soal: "Anak Nuh yang mendapat kutuk karena melihat aurat ayahnya?", jawaban: "Ham (Kejadian 9:22,24)" },
  { nomor: 727, soal: "Nama lain Salomo yang diberikan Tuhan?", jawaban: "Yedija (2Samuel 12:25)" },
  { nomor: 728, soal: "Siapakah dua pengintai yang masuk tanah Kanaan?", jawaban: "Kaleb bin Yefune dan Yosua bin Nun (Bilangan 14:30)" },
  { nomor: 729, soal: "Sayur apakah yang dimakan pada perayaan Paskah?", jawaban: "Sayur pahit" },
  { nomor: 730, soal: "Apa yang dimakan Yesus setelah kebangkitan-Nya?", jawaban: "Sepotong ikan goreng" },
  { nomor: 731, soal: "Berapa roti dan ikan untuk memberi makan 5000orang?", jawaban: "Lima roti dan dua ikan" },
  { nomor: 732, soal: "Di kota manakah Yesus menyembuhkan orang kerasukan di rumah ibadat?", jawaban: "Kapernaum" },
  { nomor: 733, soal: "Dimana tertulis bahwa akar segala kejahatan ialah cinta uang?", jawaban: "1Timotius 6:10" },
  { nomor: 734, soal: "Sungai apakah yang berubah menjadi darah?", jawaban: "Sungai Nil" },
  { nomor: 735, soal: "Apa arti Imanuel?", jawaban: "Allah menyertai kita" },
  { nomor: 736, soal: "Binatang apakah yang melambangkan keselamatan dan kesetiaan?", jawaban: "Burung merpati" },
  { nomor: 737, soal: "Burung apakah yang pertama dilepaskan Nuh?", jawaban: "Burung gagak (Kejadian 8:7)" },
  { nomor: 738, soal: "Seperti pohon apakah orang benar dilambangkan?", jawaban: "Pohon kurma (Mazmur 92:13)" },
  { nomor: 739, soal: "Batang tumbuhan apakah yang diunjukkan ke mulut Yesus menjelang kematian-Nya?", jawaban: "Hisop" },
  { nomor: 740, soal: "Daun apakah yang digunakan menyambut Yesus ke Yerusalem?", jawaban: "Daun palem" },
  { nomor: 741, soal: "Menurut Kidung Agung,apakah yang tidak dapat dihanyutkan sungai?", jawaban: "Cinta" },
  { nomor: 742, soal: "Gunung apakah di Yerusalem yang sering disebut dalam Alkitab?", jawaban: "Gunung Sion" },
  { nomor: 743, soal: "Dimanakah Yesus menyampaikan khotbah terakhir-Nya?", jawaban: "Bukit Zaitun" },
  { nomor: 744, soal: "Sebutkan tujuh ucapan Yesus di kayu salib!", jawaban: "Ya Bapa ampunilah mereka;Hari ini engkau bersama-Ku di Firdaus;Ibu inilah anakmu;Eli Eli lama sabakhtani;Aku haus;Sudah selesai;Ya Bapa ke dalam tangan-Mu Kuserahkan nyawa-Ku" },
  { nomor: 745, soal: "Sebutkan ukuran timbangan dalam Alkitab!", jawaban: "Talenta =60mina =±34kg;Mina =50syikal =±0,6 kg;Syikal =2beka =±11,5g;Beka =10gera =±5,7g;Gera =±0,6g" },
  { nomor: 746, soal: "Sebutkan ukuran panjang dalam Alkitab!", jawaban: "Hasta ±45cm;Jengkal ±23cm;Setapak tangan ±7,3cm;Mil Romawi ±1,5km;Stadia ±200m;Depa ±1,85m" },
  { nomor: 747, soal: "Sebutkan ukuran isi kering dalam Alkitab!", jawaban: "Homer/Kor =10efa =±220l;Efa =10gomer =±22l; Gomer =1/10efa =±2l;Kab =1/18efa =±1l" },
  { nomor: 748, soal: "Sebutkan ukuran isi cair dalam Alkitab!", jawaban: "Bat =±220l;Hin =1/16bat =±4l;Log =1/72bat =±0,3l" },
];