export const soalData = [
  { nomor: 1, soal: "Siapakah nama raja pertama bangsa Israel?", jawaban: "Saul" },
  { nomor: 2, soal: "Siapakah nama raja yang terkenal dengan hikmat dan kebijaksanaannya?", jawaban: "Salomo" },
  { nomor: 4, soal: "Siapakah raja yang bunuh diri dengan membakar istananya sendiri?", jawaban: "Zimri" },
  { nomor: 5, soal: "Siapakah raja yang naik tahta dengan umur termuda?", jawaban: "Yoas" },
  { nomor: 6, soal: "Siapakah raja Asyur yang dibunuh oleh anak-anaknya di kuil?", jawaban: "Sanherib" },
  { nomor: 7, soal: "Siapakah nama cucu dari Raja Saul,yang kakinya timpang?", jawaban: "Mefiboset" },
  { nomor: 8, soal: "Siapakah nama ayah dari Raja Saul?", jawaban: "Kish" },
  { nomor: 9, soal: "Siapakah nama hakim pertama bangsa israel?", jawaban: "Otniel" },
  { nomor: 10, soal: "Siapakah nama hakim yang bertangan kidal?", jawaban: "Ehud" },
  { nomor: 11, soal: "Siapakah nama nabi yang memakan gulungan kitab,yang di mulutnya berasa manis seperti madu tetapi kemudian di perutnya terasa pahit?", jawaban: "Yohanes" },
  { nomor: 12, soal: "Siapakah nama nabiah yang terkena kusta?", jawaban: "Miryam" },
  { nomor: 13, soal: "Siapakah nabi yang menikahi perempuan sundal?", jawaban: "Hosea" },
  { nomor: 14, soal: "Siapakah nama nabi yang memperingatkan Daud tentang dosa perzinahannya?", jawaban: "Natan" },
  { nomor: 15, soal: "Siapakah nama nabi yang pekerjaannya sebagai peternak dan pemungut buah ara?", jawaban: "Amos" },
  { nomor: 16, soal: "Siapakah nabi yang berjalan telanjang dan tak berkasut 3tahun lamanya?", jawaban: "Yesaya" },
  { nomor: 17, soal: "Siapakah nama bujang dari nabi Elisa?", jawaban: "Gehazi" },
  { nomor: 19, soal: "Siapakah nama wanita yang dibangkitkan oleh Petrus?", jawaban: "Dorkas" },
  { nomor: 20, soal: "Siapakah nama orang yang jatuh dari jendela saat Paulus berkotbah?", jawaban: "Eutikhus" },
  { nomor: 21, soal: "Siapakah nama ayah dari murid Yesus yang disebut Boarnerges?", jawaban: "Zebedeus" },
  { nomor: 23, soal: "Siapakah nama murid Yesus yang diketahui menikah dalam alkitab?", jawaban: "Petrus" },
  { nomor: 24, soal: "Dimana tempat Yakub bergumul dengan Tuhan hingga sendi pangkal pahanya terpelecok?", jawaban: "Pniel" },
  { nomor: 25, soal: "Apa nama sungai yang dibelah oleh Elisa dengan menggunakan jubah Elia?", jawaban: "Sungai Yordan" },
  { nomor: 26, soal: "Dalam kitab wahyu,jemaat mana yang disebutkan suam-suam kuku?", jawaban: "Laodikia" },
  { nomor: 28, soal: "Dimanakah tempat yang terdapat 12mata air dan 7pohon korma?", jawaban: "Elim" },
  { nomor: 29, soal: "Apa nama tempat asal Lidia si penjual kain ungu?", jawaban: "Tiatira" },
  { nomor: 30, soal: "Siapakah nama raja terakhir Yehuda?", jawaban: "Zedekia" },
  { nomor: 31, soal: "Siapakah Raja yang jatuh dari kisi-kisi kamar atas rumahnya?", jawaban: "Ahazia" },
  { nomor: 32, soal: "Siapakah Raja kedua Israel?", jawaban: "Daud" },
  { nomor: 33, soal: "Siapakah Raja Salem yang disebutkan sebagai Imam Allah yang Maha tinggi?", jawaban: "Melkisedek" },
  { nomor: 34, soal: "Siapakah Raja yang ditampar malaikat kemudian mayatnya dimakan cacing?", jawaban: "Herodes" },
  { nomor: 35, soal: "Siapakah istri Raja Israel yang mayatnya dimakan anjing?", jawaban: "Izebel" },
  { nomor: 36, soal: "Siapakah Raja Sikhem yang ditimpa batu kilangan oleh seorang wanita?", jawaban: "Abimelekh" },
  { nomor: 37, soal: "Siapakah Raja Gerar yang tertarik dengan Sara,istri Abraham?", jawaban: "Abimelekh" },
  { nomor: 38, soal: "Siapakah Hakim yang membunuh 600orang Filistin dengan tongkat penghalau lembu?", jawaban: "Samgar" },
  { nomor: 39, soal: "Siapakah nama suami dari seorang hakim wanita yang juga seorang nabiah?", jawaban: "Lapidot" },
  { nomor: 40, soal: "Siapakah nabi yang disebutkan dalam Alkitab berkepala botak?", jawaban: "Elisa" },
  { nomor: 43, soal: "Siapakah yang disuruh oleh Nabi Yeremia untuk menuliskan kitab Yeremia?", jawaban: "Barukh" },
  { nomor: 44, soal: "Siapakah nabi yang jatuh dari kursi ketika mendengar kabar kedua anaknya meninggal dan tabut Allah dirampas?", jawaban: "Eli" },
  { nomor: 45, soal: "Siapakah nama anak Nabi Nuh yang melihat ayahnya telanjang?", jawaban: "Ham" },
  { nomor: 46, soal: "Nabi yang menjadi perantara Raja Hizkia dengan Tuhan?", jawaban: "Yesaya" },
  { nomor: 47, soal: "Apa nama pohon yang ditumbuhkan Tuhan untuk menaungi Yunus?", jawaban: "Pohon Jarak" },
  { nomor: 48, soal: "Siapakah rasul yang dibunuh oleh Herodes?", jawaban: "Yakobus" },
  { nomor: 49, soal: "Siapakah nama nabi palsu yang juga tukang sihir di pulau Siprus,yang menghalangi gubernur itu utk mendengarkan Firman Allah dari Paulus dan Barnabas?", jawaban: "Elimas /Baryesus" },
  { nomor: 50, soal: "Siapakah nama murid pengganti Yudas Iskariot?", jawaban: "Matias" },
  { nomor: 51, soal: "Siapakah nama seorang yang lain yang diusulkan untuk menggantikan Yudas?", jawaban: "Yustus /Barsabas /Yusuf" },
  { nomor: 52, soal: "Siapakah nama hamba imam besar yang telinganya putus karena Petrus?", jawaban: "Malkhus" },
  { nomor: 53, soal: "Siapakah nama murid Tuhan yang diberikan penglihatan untuk mencari Saulus di rumah Yudas?", jawaban: "Ananias" },
  { nomor: 54, soal: "Dimanakah bahtera Nuh kandas?", jawaban: "Gunung Ararat" },
  { nomor: 55, soal: "Dimanakah Sara dikuburkan?", jawaban: "Gua Makhpela" },
  { nomor: 56, soal: "Dimanakah gua persembunyian Daud dari Saul?", jawaban: "Gua Adulam" },
  { nomor: 57, soal: "Dimanakah Yesus membangkitkan anak laki-laki seorang janda?", jawaban: "Nain" },
  { nomor: 58, soal: "Nama asal Daerah sida-sida yang dibaptis oleh Filipus?", jawaban: "Etiopia" },
  { nomor: 59, soal: "Di atas gunung apakah Musa mati?", jawaban: "Gunung Nebo" },
  { nomor: 60, soal: "Siapakah nama Ratu Etiopia yang sida-sidanya dibaptis oleh salah satu murid Yesus?", jawaban: "Sri" },
  { nomor: 61, soal: "Siapakah Raja yang diperpanjang umurnya 15tahun?", jawaban: "Hizkia" },
  { nomor: 62, soal: "Apa nama lain Yusuf yang diberikan oleh Firaun?", jawaban: "Zafnat Paaneah" },
  { nomor: 63, soal: "Siapakah nama anak perempuan Raja Saul yang mnejadi istri Raja Daud?", jawaban: "Mikhal" },
  { nomor: 64, soal: "Siapakah nama Raja yang pada masa pemerintahannya terjadi gempa bumi?", jawaban: "Uzia" },
  { nomor: 65, soal: "Siapakah nama Ratu yang digantikan kedudukannya oleh Ester?", jawaban: "Ratu Wasti" },
  { nomor: 68, soal: "Siapakah nama ayah Simson?", jawaban: "Manoah" },
  { nomor: 69, soal: "Siapakah nama hakim yang bernazar,sehingga akhirnya ia mengorbankan anak perempuannya untuk Tuhan?", jawaban: "Yefta" },
  { nomor: 70, soal: "Siapakah Nabi yang dihukum mati oleh Raja Yoyakim?", jawaban: "Nabi Uria" },
  { nomor: 73, soal: "Siapakan Nabi yang mabuk pertama kali oleh anggur?", jawaban: "Nuh" },
  { nomor: 74, soal: "Nama salah satu anak nabi Hosea?", jawaban: "Lo-Ruhama" },
  { nomor: 75, soal: "Nama salah satu putri Ayub?", jawaban: "Kezia/Yemima/Karenhapukh" },
  { nomor: 76, soal: "Siapakah nabi besar yang memakan gulungan kitab dan rasanya manis seperti madu?", jawaban: "Yehezkiel" },
  { nomor: 77, soal: "Apa makanan dari Yohanes pembaptis?", jawaban: "Belalang dan madu hutan" },
  { nomor: 78, soal: "Berapakah uang yang didapatkan oleh Simon Petrus di dalam mulut ikan pancingannya?", jawaban: "4" },
  { nomor: 79, soal: "Dengan berapa keping perak,Yudas menjual Yesus?", jawaban: "30keping uang perak" },
  { nomor: 80, soal: "Siapakah nama ketiga murid yang ikut berdoa dengan Yesus di taman Getsemani?", jawaban: "Yohanes," },
  { nomor: 81, soal: "Siapakah nama guru dari rasul Paulus?", jawaban: "Gamaliel" },
  { nomor: 82, soal: "Siapakah nama perwira pasukan Italia yang dibaptis oleh Petrus?", jawaban: "Kornelius" },
  { nomor: 83, soal: "Sipakah nama orang lumpuh dari Lida yang disembuhkan oleh Petrus?", jawaban: "Eneas" },
  { nomor: 84, soal: "Dimana Nabi Elisa membangkitkan seorang anak?", jawaban: "sunem" },
  { nomor: 85, soal: "Dimana tempat Yohanes mendapatkan penglihatan mengenai akhir zaman?", jawaban: "Pulau Patmos" },
  { nomor: 86, soal: "Di kota manakah Barnabas disebut dewa Zeus dan Paulus disebut dewa Hermes?", jawaban: "Listra" },
  { nomor: 87, soal: "Dimanakah Paulus mencukur rambutnya?", jawaban: "Kengkrea" },
  { nomor: 88, soal: "Setelah membunuh Habel,Kain menetap dimana?", jawaban: "Tanah Nod" },
  { nomor: 89, soal: "Dimanakah abraham akan mempersembahkan anaknya,Ishak?", jawaban: "Tanah Moria" },
  { nomor: 90, soal: "Dimanakah Terah meninggal?", jawaban: "Haran" },
  { nomor: 91, soal: "Apa yang diciptakan pada hari ke-5?", jawaban: "Binatang air dan udara" },
  { nomor: 93, soal: "Siapakah nama kedua anak Yusuf,sang raja Mesir?", jawaban: "Manasye dan Efraim" },
  { nomor: 94, soal: "Apakah tulah ke-5?", jawaban: "Penyakit sampar pada ternak" },
  { nomor: 95, soal: "Warna apakah yang pertama kali disebutkan dalam alkitab?", jawaban: "Hijau" },
  { nomor: 98, soal: "Berapa lama air bah menguasai bumi?", jawaban: "150hari" },
  { nomor: 99, soal: "Kayu apa yang digunakan sebagai bahan dasar pembuatan bahtera?", jawaban: "Kayu Gofir" },
  { nomor: 100, soal: "Dengan apakah barah Raja Hizkia disembuhkan?", jawaban: "Kue Ara" },
  { nomor: 101, soal: "Berapakah jumlah pengintai yang dikirim Musa untuk mengintai tanah Kanaan?", jawaban: "12" },
  { nomor: 102, soal: "Siapakah nama istri dari Saul?", jawaban: "Ahinoam" },
  { nomor: 103, soal: "Berapakah ukuran panjang,lebar,dan tinggi bahtera Nuh?", jawaban: "panjang 300hasta,lebar 50hasta," },
  { nomor: 104, soal: "Berapa kali bangsa Israel mengelilingi tembok Yerikho hingga runtuh?", jawaban: "13kali" },
  { nomor: 105, soal: "Berapa bakul yang tersisa ketika Tuhan Yesus memberi makan 4000orang?", jawaban: "7bakul" },
  { nomor: 107, soal: "Siapakah yang mengakui dosanya kepada malaikat Tuhan,yang pada mulanya hanya dilihat oleh keledainya?", jawaban: "Bileam" },
  { nomor: 110, soal: "Siapakah Raja yang juga penyair dan pemain musik,yang telah mempermalukan istrinya dengan meloncat-loncat serta menari-nari di jalan?", jawaban: "Daud" },
  { nomor: 112, soal: "Dimanakah murid-murid Tuhan untuk pertama kalinya disebut orang Kristen?", jawaban: "Antiokhia" },
  { nomor: 114, soal: "Burung apakah yang pertama kali dilepaskan oleh Abraham ketika air bah mulai surut?", jawaban: "Gagak" },
  { nomor: 116, soal: "Di pulau manakah Paulus dipagut tangannya oleh seekor ular berbisa?", jawaban: "Malta" },
  { nomor: 117, soal: "Siapakah keturunan Saul yang mengutuki Daud?", jawaban: "Simei" },
  { nomor: 118, soal: "Siapakah nama istri Abraham yang kedua setelah kematian Sara?", jawaban: "Ketura" },
  { nomor: 120, soal: "Henokh merupakan salah satu orang yang tidak mengalami kematian karena dia secara langsung diangkat oleh Allah.Siapakah nama kakek dari Henokh?", jawaban: "Mahalaleel" },
  { nomor: 121, soal: "Siapakah nama salah satu anak dari nabi Hosea?", jawaban: "Yizreel,Lo-Ami,Lo Ruhama" },
  { nomor: 123, soal: "Siapakah nama seorang perempuan sundal yang menjadi istri dari nabi Hosea?", jawaban: "Gomer" },
  { nomor: 125, soal: "Siapakah nama anak dari nabi Yesaya?", jawaban: "Maher-Syalal Hash-Bas" },
  { nomor: 126, soal: "Siapakah nama rekan sekerja Paulus yang disebut sebagai dewa Zeus di Listra?", jawaban: "Barnabas" },
  { nomor: 127, soal: "Dimanakah daerah tempat saul dilahirkan?", jawaban: "Gibea" },
  { nomor: 128, soal: "Siapakah nama ibu dari Timotius?", jawaban: "Eunike" },
  { nomor: 129, soal: "Tulisan di dinding istana raja Belsyazar yang kemudian diterjemahkan oleh Daniel?", jawaban: "Mene mene tekel ufarsin" },
  { nomor: 130, soal: "Apa bunyi dari Matius 28:19–20?", jawaban: "Karena itu pergilah,jadikanlah semua bangsa murid-Ku dan" },
  { nomor: 131, soal: "Apa arti Golgota?", jawaban: "Tempat Tengkorak" },
  { nomor: 132, soal: "Apa arti \"Eli-Eli lama sabakhtani\"dan terdapat pada?", jawaban: "Allah-Ku,Allah-Ku,mengapa Engkau" },
  { nomor: 133, soal: "Siapa nama murid yang paling dikasihi Yesus?", jawaban: "Yohanes" },
  { nomor: 134, soal: "Pada umur berapakah Yesus mulai mengajar?", jawaban: "12tahun" },
  { nomor: 135, soal: "Apa arti \"INRI\"?", jawaban: "Inilah Raja Orang Yahudi" },
  { nomor: 136, soal: "Dimanakah Yesus disalibkan?", jawaban: "Di Bukit Golgota" },
  { nomor: 137, soal: "Tuhan Yesus dijual seharga?", jawaban: "30keping perak" },
  { nomor: 138, soal: "Di mana Tuhan Yesus ditangkap?", jawaban: "Taman Getsemani" },
  { nomor: 139, soal: "Sesudah menyanyikan nyanyian pujian,Yesus dan murid-murid-Nya pergi ke bukit?", jawaban: "Bukit Zaitun 140.Berapa kali Petrus menyangkal Yesus?3kali sebelum ayam berkokok" },
  { nomor: 142, soal: "Apa arti Kefas?", jawaban: "Petrus" },
  { nomor: 143, soal: "Apa arti Mesias?", jawaban: "Kristus" },
  { nomor: 144, soal: "Apa arti Rabi?", jawaban: "Guru" },
  { nomor: 145, soal: "Siapakah yang mengkhianati Yesus?", jawaban: "Yudas Iskariot" },
  { nomor: 147, soal: "Dari mana Yesus berasal?", jawaban: "Nazaret" },
  { nomor: 148, soal: "Apa arti Boanerges?", jawaban: "Anak-anak guruh" },
  { nomor: 149, soal: "Siapakah yang membaptis Yesus?", jawaban: "Yohanes Pembaptis" },
  { nomor: 151, soal: "Siapakah yang menjadi tiang garam?", jawaban: "Istri Lot" },
  { nomor: 152, soal: "Siapa nama ibu Ismail?", jawaban: "Hagar" },
  { nomor: 153, soal: "Apa arti Ishak?", jawaban: "Tertawa" },
  { nomor: 156, soal: "Siapa yang membawa orang Israel keluar dari Tanah Mesir?", jawaban: "Musa" },
  { nomor: 157, soal: "Siapa nama istri Musa?", jawaban: "Zipora" },
  { nomor: 158, soal: "Di mana terdapat hukum yang terutama?", jawaban: "Matius 22:37–40" },
  { nomor: 159, soal: "Apa bunyi Wahyu 2:10b?", jawaban: "Hendaklah engkau setia sampai mati dan Aku akan mengaruniakan" },
  { nomor: 160, soal: "Siapakah yang diangkat oleh Mordekhai sebagai anaknya?", jawaban: "Ester" },
  { nomor: 161, soal: "Sebutkan ke-9buah Roh dan terdapat pada?", jawaban: "Kasih,sukacita,damai sejahtera,kesabaran," },
  { nomor: 162, soal: "Apa arti Sola Gratia?", jawaban: "Hanya oleh anugerah kita diselamatkan" },
  { nomor: 163, soal: "Apa arti Sola Fide?", jawaban: "Hanya oleh iman kita dibenarkan" },
  { nomor: 164, soal: "Apa arti Sola Scriptura?", jawaban: "Alkitab adalah Firman Allah" },
  { nomor: 165, soal: "Apa arti Alfa dan Omega?", jawaban: "Yang awal dan yang akhir" },
  { nomor: 166, soal: "Berapa jumlah kitab PL dan PB?", jawaban: "PL 39kitab dan PB 27kitab" },
  { nomor: 167, soal: "Terdiri atas berapa pasal Kitab Obaja?", jawaban: "1pasal" },
  { nomor: 168, soal: "Apa arti Petrus?", jawaban: "Batu karang" },
  { nomor: 169, soal: "Di manakah terdapat Doa Bapa Kami?", jawaban: "Matius 6:9–13" },
  { nomor: 170, soal: "Apa arti Samuel?", jawaban: "Anak yang diminta" },
  { nomor: 171, soal: "Siapa nama istri Uria?", jawaban: "Batsyeba 172.Apa nama kitab sebelum Mikha?Yunus 173.Di dalam KJ nomor berapakah lagu \"Pada Kaki Salib-Mu\"?KJ No.368174.Apa bunyi 1Timotius 4:12?Jangan seorang pun menganggap engkau rendah karena engkau muda,jadilah teladan bagi orang-orang percaya dalam perkataan,tingkah laku,kasih,kesetiaan," },
  { nomor: 175, soal: "Siapakah yang dimasukkan ke dalam perapian yang menyala-nyala?", jawaban: "Sadrakh,Mesakh,dan Abednego" },
  { nomor: 176, soal: "Apa arti Efrata?", jawaban: "Terbukalah 177.Apa arti Hosea?Hamba Tuhan 178.Apa arti Rut?Teman atau sahabat 179.Dalam Filipi 1:21dikatakan \"Karena bagiku hidup adalah ...dan mati adalah ...\"?Kristus dan keuntungan" },
  { nomor: 181, soal: "\"Takut akan TUHAN adalah permulaan pengetahuan...\"terdapat di mana?", jawaban: "Amsal 1:7182.Apa arti \"Ora et labora\"?Berdoa dan bekerja 183.Apa arti Matius?Pemberian Allah 184.Apakah pekerjaan Matius sebelum mengikut Yesus?Pemungut cukai 185.Kepada siapakah Injil Lukas ditujukan?Theofilus 186.Yesus lahir di kota?Betlehem 187.Mujizat air menjadi anggur terjadi di kota?Kana 188.Siapakah penulis Kitab Wahyu?Yohanes 189.Siapakah penulis Kitab Kisah Para Rasul?Lukas 190.\"Hormatilah ayah dan ibumu\"adalah hukum Taurat ke berapa?Hukum Taurat ke-5191.\"Terang\"diciptakan pada hari ke berapa?Hari pertama 192.Berapakah jumlah pasal dalam Kitab Kejadian?50pasal 193.Apa yang dimaksud dengan Imago Dei?Segambar dan serupa dengan Allah 194.Berapa tahun bangsa Israel menuju Tanah Kanaan?40tahun 195.Di manakah Tuhan Yesus dibaptis?Sungai Yordan 196.Pada umur berapakah Tuhan Yesus disunat?8hari 197.Melalui siapakah semua bangsa memperoleh kelepasan?Abraham 198.Apa arti Zet?Pengganti 199.Apa arti Abraham?Bapa segala orang percaya 200.Sebutkan nama anak-anak Nuh!Sem,Ham,dan Yafet 201.Siapakah yang menjual hak kesulungannya demi semangkuk kacang merah?Esau 202.Apa arti Yakub?Penipu 203.Apa arti Esau?Berbulu 204.Apa arti Musa?Anak yang diangkat dari air 205.Apa sajakah yang dipersembahkan oleh orang-orang Majus dari timur?Emas,kemenyan,dan mur" },
  { nomor: 206, soal: "Apakah yang dikatakan di dalam Yakobus 1:8?", jawaban: "Sebab orang yang mendua hati tidak akan tenang dalam hidupnya" },
  { nomor: 207, soal: "\"Hai pemalas,pergilah kepada semut,perhatikanlah lakunya dan jadilah bijak.\"Di mana nats ini terletak?", jawaban: "Amsal 6:6" },
  { nomor: 208, soal: "Berapa kalikah kata \"mengajar\"digunakan dalam Kitab Matius?", jawaban: "9kali 209.Siapakah yang dijadikan sebagai penjala manusia?Simon Petrus 210.Mengapa Yesus disebut sebagai Guru Agung?Karena hakekat pribadi-Nya sendiri 211.Pada hari ke berapakah Tuhan menciptakan manusia?Hari ke-6212.Dalam Ibrani 7:2,apakah arti nama Melkisedek?Raja kebenaran dan Raja damai sejahtera 213.Siapakah yang menggantikan Yesus memikul salib-Nya?Simon dari Kirene 214.Berapa orang yang dipilih untuk melayani orang miskin?7orang 215.Siapakah nama ibu Benyamin?Rahel 216.Apa arti Pentakosta?Hari turunnya Roh Kudus 217.Di manakah pasal dan ayat terpendek dalam Alkitab?Mazmur 117:1–2218.Apa bunyi Mazmur 119:105?Firman-Mu itu pelita bagi kakiku dan terang bagi jalanku 219.Di manakah Hukum Taurat selain Keluaran 20?Ulangan 4:11–12" },
  { nomor: 220, soal: "Apa inti dari seluruh Hukum Taurat?", jawaban: "Kasih" },
  { nomor: 221, soal: "Terbuat dari apakah bahtera Nuh?", jawaban: "Kayu gofir" },
  { nomor: 222, soal: "Di manakah bahtera Nuh kandas?", jawaban: "Gunung Ararat" },
  { nomor: 223, soal: "Berapakah ukuran bahtera Nuh?", jawaban: "300hasta panjangnya,50hasta lebarnya,dan 30hasta" },
  { nomor: 224, soal: "Burung apa yang turun saat Yesus dibaptis?", jawaban: "Burung merpati" },
  { nomor: 225, soal: "Apa bunyi Ibrani 11:1?", jawaban: "Iman adalah dasar dari segala sesuatu yang kita harapkan dan bukti dari segala sesuatu yang tidak kita lihat" },
  { nomor: 226, soal: "\"Pergaulan yang buruk merusakkan kebiasaan yang baik\"terdapat dalam kitab apa?", jawaban: "1Korintus 15:33" },
  { nomor: 227, soal: "Siapakah yang mati sehingga Petrus dilepaskan dari penjara?", jawaban: "Yakobus" },
  { nomor: 228, soal: "Siapakah yang disebut pasukan Italia?", jawaban: "Kornelius" },
  { nomor: 229, soal: "Siapakah yang terbunuh saat Saulus hadir?", jawaban: "Stefanus" },
  { nomor: 230, soal: "Apa yang dikenakan Adam dan Hawa setelah berdosa?", jawaban: "Daun pohon ara" },
  { nomor: 231, soal: "Berapa lama air bah menutupi bumi?", jawaban: "150hari" },
  { nomor: 232, soal: "Apa nama kasih antara orang tua dan anak?", jawaban: "Storge" },
  { nomor: 233, soal: "Siapakah murid Yesus yang ingin dibasuh kakinya?", jawaban: "Petrus" },
  { nomor: 234, soal: "Siapakah penjual kain ungu?", jawaban: "Lidya" },
  { nomor: 235, soal: "Siapa nama ayah Daud?", jawaban: "Isai" },
  { nomor: 236, soal: "Siapakah hakim perempuan di Israel?", jawaban: "Debora" },
  { nomor: 237, soal: "Siapakah perempuan yang menyelamatkan bangsanya dari pembantaian?", jawaban: "Ester" },
  { nomor: 238, soal: "Siapa orang tua Martin Luther?", jawaban: "Hans Luther dan Katerina von Bora" },
  { nomor: 239, soal: "Apa arti Daud?", jawaban: "Yang dikasihi" },
  { nomor: 240, soal: "Apa arti Yehezkiel?", jawaban: "Allah menguatkan" },
  { nomor: 241, soal: "Apa arti Gideon?", jawaban: "Pahlawan yang gagah berani" },
  { nomor: 242, soal: "Apa arti Onesimus?", jawaban: "Yang berguna" },
  { nomor: 243, soal: "Apa arti Adam?", jawaban: "Yang dibuat dari tanah" },
  { nomor: 244, soal: "Apa arti Akwila?", jawaban: "Burung rajawali" },
  { nomor: 245, soal: "Apa arti Talita kum?", jawaban: "Hai anak perempuan,bangkitlah" },
  { nomor: 246, soal: "Siapa pengarang lagu KJ 64\"Bila Kulihat Bintang Gemerlapan\"?", jawaban: "Gustaf Boberg" },
  { nomor: 247, soal: "Pada usia berapa Yesus wafat?", jawaban: "30tahun" },
  { nomor: 248, soal: "Di manakah Taman Getsemani?", jawaban: "Seberang Sungai Kidron" },
  { nomor: 249, soal: "Apa mukjizat pertama Yesus?", jawaban: "Mengubah air menjadi anggur" },
  { nomor: 250, soal: "Siapakah murid yang memotong telinga hamba Imam Besar?", jawaban: "Petrus" },
  { nomor: 251, soal: "Siapakah nama hamba Imam Besar itu?", jawaban: "Malkhus" },
  { nomor: 252, soal: "Apa hukum yang terutama dan pertama?", jawaban: "Kasihilah Tuhan Allahmu dengan segenap hatimu," },
  { nomor: 253, soal: "Siapakah yang meminta jenazah Yesus kepada Pilatus?", jawaban: "Yusuf dari Arimatea" },
  { nomor: 254, soal: "Bersama siapa Yusuf mengafani Yesus?", jawaban: "Nikodemus" },
  { nomor: 255, soal: "Dengan apakah Maria mengolesi kaki Yesus?", jawaban: "Minyak narwastu murni" },
  { nomor: 256, soal: "Siapa dua murid yang datang ke kubur lalu pulang lebih dulu?", jawaban: "Simon Petrus dan Yohanes" },
  { nomor: 257, soal: "Apa yang Yesus lakukan sebelum Perjamuan Terakhir?", jawaban: "Membasuh kaki murid-murid" },
  { nomor: 258, soal: "Ke mana malaikat menyuruh murid-murid bertemu Yesus?", jawaban: "Galilea" },
  { nomor: 259, soal: "Apa yang dilakukan sebelas murid saat Yesus menampakkan diri?", jawaban: "Sedang makan bersama" },
  { nomor: 260, soal: "Seseorang harus dilahirkan dari apa menurut Yesus?", jawaban: "Air dan Roh" },
  { nomor: 261, soal: "Siapa dua tokoh PL yang tidak mati?", jawaban: "Henokh dan Elia" },
  { nomor: 262, soal: "Siapa murid di Danau Tiberias saat Yesus menampakkan diri?", jawaban: "Simon Petrus,Tomas,Natanael,Yakobus,dan Yohanes" },
  { nomor: 263, soal: "Berapa jumlah ikan hasil tangkapan di Danau Tiberias?", jawaban: "153ekor" },
  { nomor: 264, soal: "Siapakah nabi yang dipenggal kepalanya?", jawaban: "Yohanes Pembaptis" },
  { nomor: 265, soal: "Di mana orang buta disuruh membasuh diri?", jawaban: "Kolam Siloam" },
  { nomor: 266, soal: "Siapakah yang disembah sebagai dewa setelah dipatuk ular?", jawaban: "Paulus" },
  { nomor: 267, soal: "Siapakah orang tertua di Alkitab?", jawaban: "Metusalah" },
  { nomor: 268, soal: "Siapakah yang dibebaskan malaikat dari penjara?", jawaban: "Petrus" },
  { nomor: 269, soal: "Siapakah juru minuman raja yang membangun tembok Yerusalem?", jawaban: "Nehemia" },
  { nomor: 270, soal: "Suku Israel manakah yang menjadi imam?", jawaban: "Lewi" },
  { nomor: 271, soal: "Siapakah misionaris terbesar PB?", jawaban: "Paulus" },
  { nomor: 272, soal: "Di kota manakah Yesus diurapi dengan minyak mahal?", jawaban: "Betania" },
  { nomor: 273, soal: "Siapakah murid yang menyebut pengurapan itu pemborosan?", jawaban: "Yudas Iskariot" },
  { nomor: 274, soal: "Apa kata Yesus saat membagi roti?", jawaban: "Ambillah,makanlah,inilah tubuh-Ku" },
  { nomor: 275, soal: "Ke mana Yudas membuang 30keping perak?", jawaban: "Bait Suci" },
  { nomor: 276, soal: "Untuk apa uang itu digunakan para imam?", jawaban: "Membeli tanah tukang periuk" },
  { nomor: 277, soal: "Siapakah yang mengirim pesan kepada Pilatus agar tidak mencampuri perkara Yesus?", jawaban: "Istri" },
  { nomor: 278, soal: "Di manakah terdapat sumur Yakub?", jawaban: "Kota Sikhar,Samaria" },
  { nomor: 279, soal: "Siapakah yang dikenal sebagai nabi yang meratap?", jawaban: "Yeremia" },
  { nomor: 280, soal: "Apa yang dibawa Nikodemus ketika datang kepada Yesus?", jawaban: "Campuran minyak mur dan minyak" },
  { nomor: 281, soal: "Siapakah nabi PL yang diperintahkan menikah dengan seorang pelacur?", jawaban: "Hosea" },
  { nomor: 282, soal: "Siapakah dua gembala jemaat penerima surat Paulus?", jawaban: "Timotius dan Titus" },
  { nomor: 283, soal: "Siapakah orang yang menderita hebat tetapi tetap percaya kepada Allah?", jawaban: "Ayub" },
  { nomor: 284, soal: "Siapakah nama ayah Abraham?", jawaban: "Terah" },
  { nomor: 285, soal: "Kata apakah dalam PB yang berarti diurapi oleh Tuhan?", jawaban: "Kristus" },
  { nomor: 286, soal: "Siapakah dua orang yang berjalan di atas air?", jawaban: "Yesus dan Petrus" },
  { nomor: 288, soal: "Ke manakah dua bangsa umat Allah dibuang?", jawaban: "Israel ke Asyur dan Yehuda ke Babel" },
  { nomor: 289, soal: "Siapakah raja paling berhikmat di dunia?", jawaban: "Salomo" },
  { nomor: 290, soal: "Surat apakah yang dikenal sebagai surat sukacita?", jawaban: "Filipi" },
  { nomor: 291, soal: "Di manakah terdapat Doa Bapa Kami?", jawaban: "Matius 6:9–13" },
  { nomor: 292, soal: "Apa bunyi Yohanes 15:1?", jawaban: "Akulah pokok anggur yang benar dan Bapa-Kulah pengusahanya" },
  { nomor: 293, soal: "Apa bunyi Yohanes 14:6?", jawaban: "Akulah jalan dan kebenaran dan hidup,tidak ada seorang pun yang" },
  { nomor: 294, soal: "Berapa lama kegelapan terjadi saat Yesus disalibkan?", jawaban: "Tiga jam,dari jam 12siang sampai jam 3" },
  { nomor: 295, soal: "Mukjizat apa saja yang terjadi saat Yesus wafat?", jawaban: "Kegelapan,tabir Bait Suci terbelah,gempa bumi,kubur terbuka,orang kudus bangkit" },
  { nomor: 296, soal: "Siapakah nama istri Ishak?", jawaban: "Ribka" },
  { nomor: 297, soal: "Pada usia berapakah Abraham meninggal?", jawaban: "175tahun" },
  { nomor: 298, soal: "Siapakah anak-anak Yusuf yang lahir di Mesir?", jawaban: "Manasye dan Efraim" },
  { nomor: 299, soal: "Berapa usia Yusuf saat meninggal?", jawaban: "110tahun" },
  { nomor: 300, soal: "Kota apa yang dibangun Israel untuk Firaun saat diperbudak?", jawaban: "Pitom dan Raamses" },
  { nomor: 301, soal: "Dari suku manakah Musa berasal?", jawaban: "Lewi" },
  { nomor: 302, soal: "Dalam bentuk apakah Allah pertama kali menampakkan diri kepada Musa?", jawaban: "Api" },
  { nomor: 303, soal: "Kitab Keluaran terdiri dari berapa pasal?", jawaban: "40pasal" },
  { nomor: 304, soal: "Perayaan Paskah PL diperingati sebagai apa?", jawaban: "Hari keluarnya Israel dari Mesir" },
  { nomor: 305, soal: "Saat siang hari Tuhan menuntun Israel dengan apa?", jawaban: "Tiang awan" },
  { nomor: 306, soal: "Siapakah nama mertua Musa?", jawaban: "Yitro" },
  { nomor: 307, soal: "Di gunung apakah Tuhan memberi hukum kepada Musa?", jawaban: "Gunung Sinai" },
  { nomor: 308, soal: "Di manakah Yesus pertama kali dicobai?", jawaban: "Padang gurun" },
  { nomor: 309, soal: "Penyakit apakah yang diderita mertua Petrus?", jawaban: "Demam" },
  { nomor: 310, soal: "Injil Markus terdiri dari berapa pasal?", jawaban: "16pasal" },
  { nomor: 311, soal: "Pakaian apakah yang dikenakan Yohanes Pembaptis?", jawaban: "Bulu unta" },
  { nomor: 312, soal: "Bagaimana cara Yohanes Pembaptis dibunuh?", jawaban: "Dipenggal kepalanya" },
  { nomor: 313, soal: "Siapakah nama ayah Yohanes Pembaptis?", jawaban: "Zakharia" },
  { nomor: 314, soal: "Melalui siapakah Allah memberitakan kelahiran Yesus kepada Maria?", jawaban: "Malaikat Gabriel" },
  { nomor: 315, soal: "Injil Lukas terdiri dari berapa pasal?", jawaban: "24pasal" },
  { nomor: 316, soal: "Dengan siapa Yesus berbicara saat dimuliakan di atas gunung?", jawaban: "Musa dan Elia" },
  { nomor: 317, soal: "Pada zaman kaisar siapakah Yesus lahir?", jawaban: "Kaisar Agustus" },
  { nomor: 318, soal: "Di manakah nyanyian pujian Zakharia tertulis?", jawaban: "Lukas 1:67–80" },
  { nomor: 319, soal: "Berapa lama Maria tinggal di rumah Elisabet?", jawaban: "Tiga bulan" },
  { nomor: 320, soal: "Injil Yohanes terdiri dari berapa pasal?", jawaban: "21pasal" },
  { nomor: 321, soal: "Siapakah yang dibangkitkan Yesus di kampung Maria dan Marta?", jawaban: "Lazarus" },
  { nomor: 322, soal: "Kisah Para Rasul terdiri dari berapa pasal?", jawaban: "28pasal" },
  { nomor: 323, soal: "Mengapa orang yang lemah lembut berbahagia?", jawaban: "Mereka akan memiliki bumi" },
  { nomor: 324, soal: "Apakah pelita tubuh menurut Lukas 11:34?", jawaban: "Mata" },
  { nomor: 325, soal: "Siapakah gembala pertama dalam Alkitab?", jawaban: "Habel" },
  { nomor: 326, soal: "Siapakah orang Ibrani yang menjadi penguasa di Mesir?", jawaban: "Yusuf" },
  { nomor: 327, soal: "Binatang apakah satu-satunya yang dikutuk Tuhan?", jawaban: "Ular" },
  { nomor: 328, soal: "Siapakah yang mengutuk pohon ara karena tidak berbuah?", jawaban: "Yesus" },
  { nomor: 329, soal: "Siapakah dua bidan Ibrani yang menentang perintah Firaun?", jawaban: "Pua dan Sifra" },
  { nomor: 330, soal: "Siapakah raja Israel yang pertama?", jawaban: "Saul" },
  { nomor: 331, soal: "Siapakah hakim Israel yang pertama?", jawaban: "Otniel" },
  { nomor: 332, soal: "Siapakah yang pertama menemukan bayi Musa di sungai?", jawaban: "Putri Firaun" },
  { nomor: 333, soal: "Siapakah rasul yang dibuang ke Pulau Patmos?", jawaban: "Yohanes" },
  { nomor: 334, soal: "Siapakah penulis Kitab Mazmur?", jawaban: "Daud" },
  { nomor: 335, soal: "Nama apakah yang diberikan Abraham kepada Sarai?", jawaban: "Sara" },
  { nomor: 336, soal: "Siapakah ratu yang digantikan oleh Ester?", jawaban: "Ratu Wasti" },
  { nomor: 337, soal: "Berapa lama bangsa Israel tinggal di Mesir?", jawaban: "430tahun" },
  { nomor: 338, soal: "Apakah tanda perjanjian Allah dengan Nuh?", jawaban: "Pelangi" },
  { nomor: 339, soal: "Siapakah hakim yang bertangan kidal?", jawaban: "Ehud" },
  { nomor: 340, soal: "Siapakah raja yang dibunuh oleh Ehud?", jawaban: "Raja Eglon" },
  { nomor: 341, soal: "Siapakah yang mati jatuh dari jendela saat mendengarkan khotbah?", jawaban: "Eutikhus" },
  { nomor: 342, soal: "Siapakah yang membangkitkan Eutikhus?", jawaban: "Paulus" },
  { nomor: 343, soal: "Kebun anggur milik siapa yang direbut dengan fitnah?", jawaban: "Nabot" },
  { nomor: 344, soal: "Siapakah raja yang membunuh Nabot?", jawaban: "Raja Ahab" },
  { nomor: 345, soal: "Apakah pekerjaan Kain dan Habel?", jawaban: "Kain petani dan Habel gembala" },
  { nomor: 346, soal: "Berapa lama hujan turun pada zaman Nuh?", jawaban: "40hari 40malam" },
  { nomor: 347, soal: "Apa isi perjanjian Allah dengan Nuh?", jawaban: "Tidak akan ada lagi air bah memusnahkan bumi" },
  { nomor: 348, soal: "Apa tujuan pendirian Menara Babel?", jawaban: "Mencari nama agar tidak terserak" },
  { nomor: 349, soal: "Siapakah imam yang memberkati Abraham?", jawaban: "Melkisedek" },
  { nomor: 350, soal: "Siapakah anak Abraham dari Sara dan Hagar?", jawaban: "Ishak dan Ismail" },
  { nomor: 351, soal: "Kota apa yang dimusnahkan dengan api dan belerang?", jawaban: "Sodom dan Gomora" },
  { nomor: 352, soal: "Pada usia berapakah Sara meninggal?", jawaban: "127tahun" },
  { nomor: 353, soal: "Siapakah anak-anak Ishak?", jawaban: "Esau dan Yakub" },
  { nomor: 354, soal: "Dengan apa Esau menjual hak kesulungannya?", jawaban: "Roti dan masakan kacang merah" },
  { nomor: 355, soal: "Ke mana Yakub melarikan diri setelah menipu?", jawaban: "Padan-Aram" },
  { nomor: 356, soal: "Apa nama lain Betel?", jawaban: "Kota Lus" },
  { nomor: 357, soal: "Siapakah istri-istri Yakub?", jawaban: "Rahel dan Lea" },
  { nomor: 358, soal: "Apa arti Pniel?", jawaban: "Tempat Yakub melihat Allah berhadapan muka" },
  { nomor: 359, soal: "Apa dua mimpi Yusuf?", jawaban: "Berkas gandum sujud dan matahari bulan sebelas bintang sujud" },
  { nomor: 360, soal: "Istri siapakah yang memfitnah Yusuf?", jawaban: "Istri Potifar" },
  { nomor: 361, soal: "Apa arti mimpi Firaun?", jawaban: "Tujuh tahun kelimpahan dan tujuh tahun kelaparan" },
  { nomor: 362, soal: "Nama lain apakah yang diberikan Firaun kepada Yusuf?", jawaban: "Zafnat-Paaneah" },
  { nomor: 363, soal: "Siapakah istri Yusuf?", jawaban: "Asnat" },
  { nomor: 364, soal: "Siapakah anak-anak Yusuf?", jawaban: "Manasye dan Efraim" },
  { nomor: 365, soal: "Apa pekerjaan Musa sebelum dipanggil Tuhan?", jawaban: "Gembala domba" },
  { nomor: 366, soal: "Di gunung apakah Allah mengutus Musa?", jawaban: "Gunung Horeb" },
  { nomor: 367, soal: "Laut apakah yang dibelah Tuhan?", jawaban: "Laut Teberau" },
  { nomor: 368, soal: "Di mana terdapat 12mata air dan 70pohon korma?", jawaban: "Elim" },
  { nomor: 369, soal: "Apa nama roti di padang gurun?", jawaban: "Manna" },
  { nomor: 370, soal: "Apa nama daging yang dimakan Israel di padang gurun?", jawaban: "Burung puyuh" },
  { nomor: 371, soal: "Di mana Israel mencobai Tuhan?", jawaban: "Masa dan Meriba" },
  { nomor: 372, soal: "Siapakah mertua Musa?", jawaban: "Yitro" },
  { nomor: 373, soal: "Apa yang dibuat Israel dan Harun saat Musa di Sinai?", jawaban: "Anak lembu emas" },
  { nomor: 374, soal: "Siapakah yang dipilih Tuhan membangun Kemah Suci?", jawaban: "Bezaleel dan Aholiab" },
  { nomor: 375, soal: "Siapakah nama ayah dan ibu Yesus?", jawaban: "Ibu Maria dan ayah Yusuf" },
  { nomor: 376, soal: "Persembahan apa yang dibawa orang Majus dari timur?", jawaban: "Emas,kemenyan,dan mur" },
  { nomor: 377, soal: "Apa pakaian dan makanan Yohanes Pembaptis?", jawaban: "Jubah bulu unta,ikat pinggang kulit,belalan dan madu hutan" },
  { nomor: 378, soal: "Peristiwa apa yang terjadi setelah Yesus dibaptis?", jawaban: "Langit terbuka,Roh Kudus turun seperti" },
  { nomor: 379, soal: "Berapa lama Yesus berpuasa di padang gurun?", jawaban: "40hari 40malam" },
  { nomor: 380, soal: "Apa yang ditunggangi Yesus saat dielu-elukan di Yerusalem?", jawaban: "Keledai" },
  { nomor: 381, soal: "Apa yang dikenakan di kepala Yesus saat disalibkan?", jawaban: "Mahkota duri" },
  { nomor: 382, soal: "Ibu siapa yang disembuhkan Yesus dari demam?", jawaban: "Ibu mertua Simon Petrus" },
  { nomor: 383, soal: "Siapakah pemungut cukai yang mengikuti Yesus?", jawaban: "Lewi anak Alfeus" },
  { nomor: 384, soal: "Sisa berapa bakul setelah Yesus memberi makan 5000orang?", jawaban: "12bakul" },
  { nomor: 385, soal: "Apa jawaban Petrus saat Yesus bertanya \"Siapakah Aku ini\"?", jawaban: "Engkau adalah Mesias" },
  { nomor: 386, soal: "Apa yang dilakukan Yesus terhadap pedagang di Bait Allah?", jawaban: "Mengusir mereka dan membalikkan meja" },
  { nomor: 387, soal: "Berapa persembahan janda miskin?", jawaban: "Dua peser" },
  { nomor: 388, soal: "Siapakah orang tua Yohanes Pembaptis?", jawaban: "Zakharia dan Elisabet" },
  { nomor: 389, soal: "Siapakah orang bertubuh pendek yang ingin melihat Yesus?", jawaban: "Zakheus" },
  { nomor: 390, soal: "Kepada siapa Yesus berkata tentang lahir dari air dan Roh?", jawaban: "Nikodemus" },
  { nomor: 391, soal: "Siapakah yang bercakap-cakap dengan Yesus di tepi sumur?", jawaban: "Perempuan Samaria" },
  { nomor: 392, soal: "Apa kata Tomas sebelum percaya Yesus bangkit?", jawaban: "Ia tidak akan percaya sebelum melihat bekas paku" },
  { nomor: 393, soal: "Kepada siapa Yesus berkata \"Gembalakanlah domba-domba-Ku\"?", jawaban: "Simon Petrus" },
  { nomor: 394, soal: "Apa arti Matius?", jawaban: "Pemberian Allah" },
  { nomor: 395, soal: "Kitab Matius terdiri dari berapa pasal dan ayat?", jawaban: "28pasal dan 1072ayat" },
  { nomor: 396, soal: "Siapakah yang membawa Yesus ke padang gurun untuk dicobai?", jawaban: "Roh Kudus" },
  { nomor: 397, soal: "Apa jawaban Yesus tentang batu menjadi roti?", jawaban: "Manusia hidup bukan dari roti saja" },
  { nomor: 398, soal: "Apa jawaban Yesus tentang menjatuhkan diri dari bubungan?", jawaban: "Jangan mencobai Tuhan Allahmu 399.Apa jawaban Yesus tentang menyembah iblis?Engkau harus menyembah Tuhan Allahmu" },
  { nomor: 400, soal: "Ke mana Yesus menyingkir setelah Yohanes ditangkap?", jawaban: "Kapernaum" },
  { nomor: 401, soal: "Siapakah dua bersaudara yang dipanggil Yesus di danau Galilea?", jawaban: "Simon Petrus dan Andreas" },
  { nomor: 402, soal: "Yesus memanggil mereka menjadi apa?", jawaban: "Penjala manusia" },
  { nomor: 403, soal: "Apa yang Yesus lakukan saat berkeliling di Galilea?", jawaban: "Mengajar,memberitakan Injil,dan" },
  { nomor: 404, soal: "Apa isi ucapan bahagia?", jawaban: "Berbahagia orang miskin,berdukacita,lemah lembut,lapar akan" },
  { nomor: 405, soal: "Di mana terdapat ajaran garam dan terang dunia?", jawaban: "Matius 5:13–16" },
  { nomor: 406, soal: "Mengapa terang harus bercahaya?", jawaban: "Supaya orang memuliakan Bapa di sorga" },
  { nomor: 407, soal: "Di mana Doa Bapa Kami tertulis?", jawaban: "Matius 6:9–13" },
  { nomor: 408, soal: "Siapakah yang pertama disembuhkan Yesus?", jawaban: "Orang sakit kusta" },
  { nomor: 409, soal: "Siapakah yang percaya hambanya sembuh oleh sabda Yesus?", jawaban: "Perwira di Kapernaum" },
  { nomor: 410, soal: "Yesus datang bukan memanggil orang benar melainkan siapa?", jawaban: "Orang berdosa" },
  { nomor: 411, soal: "Siapakah yang menjamah jumbai jubah Yesus?", jawaban: "Perempuan pendarahan 12tahun" },
  { nomor: 412, soal: "Siapakah yang berseru \"Kasihanilah kami hai Anak Daud\"?", jawaban: "Dua orang buta" },
  { nomor: 413, soal: "Apa akibat tidak memikul salib dan mengikut Yesus?", jawaban: "Tidak layak bagi Yesus" },
  { nomor: 414, soal: "Kota apa yang dikecam Yesus karena tidak bertobat?", jawaban: "Khorazim,Betsaida,Kapernaum" },
  { nomor: 415, soal: "Apa arti benih di pinggir jalan?", jawaban: "Firman dirampas oleh si jahat" },
  { nomor: 416, soal: "Apa arti benih di tanah berbatu?", jawaban: "Iman tidak berakar dan murtad" },
  { nomor: 417, soal: "Apa arti benih di semak duri?", jawaban: "Firman terhimpit kekhawatiran dan kekayaan" },
  { nomor: 418, soal: "Apa arti benih di tanah baik?", jawaban: "Berbuah 30,60,dan 100kali lipat" },
  { nomor: 419, soal: "Sisa berapa bakul saat memberi makan 5000orang?", jawaban: "12bakul" },
  { nomor: 420, soal: "Sisa berapa bakul saat memberi makan 4000orang?", jawaban: "7bakul" },
  { nomor: 421, soal: "Siapakah murid yang diberi kunci Kerajaan Sorga?", jawaban: "Petrus" },
  { nomor: 422, soal: "Mengapa murid harus menyangkal diri?", jawaban: "Supaya memperoleh hidup sejati" },
  { nomor: 423, soal: "Siapa yang ikut Yesus ke gunung transfigurasi?", jawaban: "Petrus,Yakobus,dan Yohanes" },
  { nomor: 424, soal: "Apa yang membuat murid ketakutan di gunung?", jawaban: "Suara Allah dari awan terang" },
  { nomor: 425, soal: "Apa yang dapat dilakukan dengan iman sebesar biji sesawi?", jawaban: "Memindahkan gunung" },
  { nomor: 426, soal: "Bagaimana syarat masuk Kerajaan Sorga?", jawaban: "Bertobat dan menjadi seperti anak kecil" },
  { nomor: 427, soal: "Mengapa jangan merendahkan anak kecil?", jawaban: "Malaikat mereka memandang wajah Bapa" },
  { nomor: 428, soal: "Berapa kali harus mengampuni?", jawaban: "70kali 7" },
  { nomor: 429, soal: "Kerajaan sorga seumpama raja yang mengadakan apa?", jawaban: "Perhitungan dengan hamba" },
  { nomor: 430, soal: "Apa hukum yang terutama?", jawaban: "Mengasihi Tuhan Allah" },
  { nomor: 431, soal: "Apa hukum yang kedua?", jawaban: "Mengasihi sesama" },
  { nomor: 432, soal: "Berapa jumlah gadis bijaksana dan bodoh?", jawaban: "Lima bijaksana dan lima bodoh" },
  { nomor: 433, soal: "Mengapa gadis bodoh disebut bodoh?", jawaban: "Tidak membawa minyak" },
  { nomor: 434, soal: "Apa yang dilakukan hamba 5talenta?", jawaban: "Menghasilkan 5talenta" },
  { nomor: 435, soal: "Apa yang dilakukan hamba 2talenta?", jawaban: "Menghasilkan 2talenta" },
  { nomor: 436, soal: "Apa yang dilakukan hamba 1talenta?", jawaban: "Menyembunyikan uang dan dihukum" },
  { nomor: 437, soal: "Di mana Yesus menubuatkan Petrus menyangkal-Nya?", jawaban: "Bukit Zaitun" },
  { nomor: 438, soal: "Dengan siapa Yesus ke Getsemani?", jawaban: "Petrus,Yakobus,dan Yohanes" },
  { nomor: 439, soal: "Apa doa pertama Yesus di Getsemani?", jawaban: "Biarlah kehendak-Mu yang jadi" },
  { nomor: 440, soal: "Apa teguran Yesus kepada murid yang tidur?", jawaban: "Berjaga dan berdoalah" },
  { nomor: 441, soal: "Dalam keadaan apa murid ditemukan Yesus?", jawaban: "Tertidur" },
  { nomor: 442, soal: "Kepada siapa Yesus dibawa setelah ditangkap?", jawaban: "Kayafas" },
  { nomor: 443, soal: "Siapakah yang mengoyakkan pakaian dan berkata Yesus menghujat?", jawaban: "Kayafas" },
  { nomor: 444, soal: "Setelah Kayafas Yesus dibawa ke siapa?", jawaban: "Pilatus" },
  { nomor: 445, soal: "Apa kata Pilatus saat membasuh tangan?", jawaban: "Aku tidak bersalah" },
  { nomor: 446, soal: "Apa jawaban rakyat?", jawaban: "Biarlah darah-Nya atas kami" },
  { nomor: 447, soal: "Siapakah yang membantu memikul salib Yesus?", jawaban: "Simon dari Kirene" },
  { nomor: 448, soal: "Yesus diberi minum apa di salib?", jawaban: "Anggur bercampur empedu" },
  { nomor: 449, soal: "Siapakah perempuan yang melihat dari jauh?", jawaban: "Maria Magdalena dan Maria lainnya" },
  { nomor: 450, soal: "Dengan kain apa Yesus dikafani?", jawaban: "Kain lenan putih" },
  { nomor: 451, soal: "Siapakah yang tinggal di depan kubur Yesus?", jawaban: "Maria Magdalena dan Maria yang lain" },
  { nomor: 452, soal: "Siapakah yang datang ke kubur saat fajar?", jawaban: "Maria Magdalena dan Maria yang lain" },
  { nomor: 453, soal: "Siapakah yang menggulingkan batu kubur?", jawaban: "Malaikat Tuhan" },
  { nomor: 454, soal: "Di mana Yesus pertama kali menampakkan diri kepada murid?", jawaban: "Galilea" },
  { nomor: 455, soal: "Apa perkataan Yesus setelah kebangkitan?", jawaban: "Kepada-Ku diberikan segala kuasa" },
  { nomor: 456, soal: "Apa arti Akeldama?", jawaban: "Tanah Darah" },
  { nomor: 457, soal: "Pengajar dan penafsir Taurat disebut apa?", jawaban: "Ahli Taurat" },
  { nomor: 458, soal: "Nama iblis sebagai kepala roh jahat?", jawaban: "Beelzebul" },
  { nomor: 459, soal: "Simbol lambang penderitaan manusia?", jawaban: "Cawan" },
  { nomor: 460, soal: "Golongan Yahudi yang taat Taurat dan adat?", jawaban: "Farisi" },
  { nomor: 461, soal: "Bahasa Ibrani puji Tuhan?", jawaban: "Haleluya" },
  { nomor: 462, soal: "Perayaan pembebasan Israel dari Mesir disebut?", jawaban: "Paskah" },
  { nomor: 463, soal: "Perayaan roti tanpa ragi disebut?", jawaban: "Hari Raya Roti Tidak Beragi" },
  { nomor: 464, soal: "Golongan pendukung Herodes disebut?", jawaban: "Herodian" },
  { nomor: 465, soal: "Golongan utama dalam Mahkamah Agama?", jawaban: "Imam-imam kepala" },
  { nomor: 466, soal: "Apa arti Eklesia?", jawaban: "Perkumpulan orang yang dipanggil Allah" },
  { nomor: 467, soal: "Apa arti Mesias?", jawaban: "Yang diurapi" },
  { nomor: 468, soal: "Mengapa Yesus disebut Kristus?", jawaban: "Karena dipilih Allah sebagai Juruselamat" },
  { nomor: 469, soal: "Badan keagamaan Yahudi tertinggi disebut?", jawaban: "Mahkamah Agama" },
  { nomor: 470, soal: "Siapa saja anggota Mahkamah Agama?", jawaban: "Imam kepala,ahli Taurat,dan tua-tua" },
  { nomor: 471, soal: "Kota asal Yesus di Galilea?", jawaban: "Nazaret" },
  { nomor: 472, soal: "Cerita untuk menjelaskan hal rohani disebut?", jawaban: "Perumpamaan" },
  { nomor: 473, soal: "Siapakah gubernur Romawi Yudea tahun 26–36M?", jawaban: "Pontius Pilatus" },
  { nomor: 474, soal: "Ukuran timbangan 3000syikal disebut?", jawaban: "Talenta" },
  { nomor: 475, soal: "Apa arti Lukas?", jawaban: "Orang yang dilahirkan pada waktu fajar" },
  { nomor: 476, soal: "Siapakah pasangan suami istri pada zaman Herodes raja Yudea yang hidup benar di hadapan Allah?", jawaban: "Zakaria dari rombongan Abia dan istrinya Elisabet dari keturunan Harun" },
  { nomor: 478, soal: "Siapakah yang berjalan mendahului Tuhan dalam Roh dan kuasa Elia?", jawaban: "Yohanes" },
  { nomor: 479, soal: "Siapa nama malaikat yang diutus Allah kepada Zakaria?", jawaban: "Gabriel" },
  { nomor: 480, soal: "Apakah Zakaria percaya berita malaikat?", jawaban: "Tidak,sehingga ia menjadi bisu" },
  { nomor: 481, soal: "Berapa lama Elisabet tidak menampakkan diri setelah mengandung?", jawaban: "Lima bulan" },
  { nomor: 482, soal: "Pada bulan keenam malaikat Gabriel diutus ke kota apa?", jawaban: "Nazaret" },
  { nomor: 483, soal: "Apa nama bulan keenam?", jawaban: "Elul" },
  { nomor: 484, soal: "Kapan anak dalam rahim Elisabet melonjak kegirangan?", jawaban: "Saat Elisabet mendengar salam Maria 485.Siapa yang membantah pemberian nama Zakaria kepada Yohanes?Elisabet" },
  { nomor: 486, soal: "Kapan mulut Zakaria terbuka kembali?", jawaban: "Saat ia menulis nama Yohanes" },
  { nomor: 487, soal: "Sampai kapan Yohanes tinggal di padang gurun?", jawaban: "Sampai ia menampakkan diri kepada Israel 488.Perahu siapakah yang dinaiki Yesus di Danau Genesaret?Perahu Simon" },
  { nomor: 489, soal: "Apa perintah Yesus kepada Simon di perahunya?", jawaban: "Menolakkan perahu sedikit jauh dari pantai" },
  { nomor: 490, soal: "Apa ungkapan Yesus kepada orang lumpuh?", jawaban: "Bangunlah,angkatlah tempat tidurmu dan pulangl 491.Di Lukas berapa Yesus memanggil dua belas murid?Lukas 6:12–16" },
  { nomor: 492, soal: "Di kota manakah Yesus membangkitkan anak muda seorang janda?", jawaban: "Nain" },
  { nomor: 493, soal: "Apa yang Yesus berikan kepada dua belas murid sebelum diutus?", jawaban: "Kuasa dan tenaga" },
  { nomor: 495, soal: "Berapa jumlah murid yang diutus berdua-dua?", jawaban: "Tujuh puluh murid" },
  { nomor: 496, soal: "Sebutkan empat kota yang dikecam Yesus?", jawaban: "Khorazim,Betsaida,Tirus,dan Sidon" },
  { nomor: 497, soal: "Mengapa Yesus berkata bersukacitalah kepada 70murid?", jawaban: "Karena nama mereka terdaftar di sorga 498.Siapakah yang tergerak hatinya melihat orang dirampok?Orang Samaria yang baik hati" },
  { nomor: 499, soal: "Siapakah yang duduk dekat kaki Tuhan dan mendengar Firman?", jawaban: "Maria" },
  { nomor: 500, soal: "Siapa kepala pemungut cukai kaya di Yerikho?", jawaban: "Zakheus" },
  { nomor: 501, soal: "Apa arti ragi dalam ajaran Yesus?", jawaban: "Kemunafikan orang Farisi" },
  { nomor: 502, soal: "Dari sepuluh orang kusta siapa yang kembali bersyukur?", jawaban: "Orang Samaria" },
  { nomor: 503, soal: "Mengapa orang membawa anak-anak kecil kepada Yesus?", jawaban: "Supaya Yesus menjamah mereka" },
  { nomor: 504, soal: "Dimanakah Yesus menyelamatkan Zakheus?", jawaban: "Di rumah Zakheus" },
  { nomor: 505, soal: "Apa komitmen Zakheus kepada Yesus?", jawaban: "Memberi setengah harta kepada orang miskin dan" },
  { nomor: 506, soal: "Dalam perumpamaan mina ada berapa hamba?", jawaban: "Sepuluh hamba" },
  { nomor: 507, soal: "Berapa mina hamba pertama dan hasilnya?", jawaban: "Sepuluh mina menghasilkan sepuluh mina" },
  { nomor: 508, soal: "Berapa mina hamba kedua dan hasilnya?", jawaban: "Lima mina menghasilkan lima mina" },
  { nomor: 509, soal: "Berapa mina hamba ketiga dan hasilnya?", jawaban: "Satu mina tidak menghasilkan apa-apa" },
  { nomor: 510, soal: "Mengapa hamba ketiga tidak berbuah?", jawaban: "Karena minanya disimpan dalam sapu tangan" },
  { nomor: 511, soal: "Apa yang terjadi dengan mina hamba ketiga?", jawaban: "Diambil dan diberikan kepada yang beroleh sepuluh mina" },
  { nomor: 512, soal: "Apa kata Yesus saat memecahkan roti?", jawaban: "Inilah tubuh-Ku yang diserahkan bagi kamu" },
  { nomor: 513, soal: "Sampai kapan Yesus tidak minum hasil pokok anggur?", jawaban: "Sampai Kerajaan Allah datang" },
  { nomor: 514, soal: "Untuk apa Yesus berdoa bagi Simon?", jawaban: "Supaya imannya jangan gugur dan menguatkan saudarasaudaranya" },
  { nomor: 515, soal: "Apa kata Yesus saat Yudas mencium-Nya?", jawaban: "Engkau menyerahkan Anak Manusia dengan ciuman 516.Mengapa Herodes girang melihat Yesus?Karena sudah lama ingin melihat-Nya" },
  { nomor: 517, soal: "Apa ungkapan penjahat di salib yang sadar?", jawaban: "Yesus,ingatlah aku apabila Engkau datang sebagai Raja" },
  { nomor: 518, soal: "Apa jawaban Yesus kepada penjahat itu?", jawaban: "Hari ini engkau bersama Aku di Firdaus" },
  { nomor: 519, soal: "Apa perkataan terakhir Yesus?", jawaban: "Ya Bapa,ke dalam tangan-Mu Kuserahkan nyawa-Ku" },
  { nomor: 520, soal: "Di jalan apakah Yesus menampakkan diri setelah bangkit?", jawaban: "Jalan ke Emaus" },
  { nomor: 521, soal: "Apa yang membuat murid Emaus mengenal Yesus?", jawaban: "Saat Ia memecahkan roti" },
  { nomor: 522, soal: "Dimana Yesus terangkat ke sorga?", jawaban: "Betania" },
  { nomor: 523, soal: "Apa bunyi Yohanes 1:1?", jawaban: "Pada mulanya adalah Firman,Firman itu bersama-sama dengan Allah" },
  { nomor: 524, soal: "Siapakah dua murid Yohanes yang pertama mengikut Yesus?", jawaban: "Andreas dan Simon Petrus" },
  { nomor: 525, soal: "Mujizat kedua Yesus di Kapernaum adalah?", jawaban: "Menyembuhkan anak pegawai istana" },
  { nomor: 526, soal: "Dimana kolam Bethesda terletak?", jawaban: "Di Yerusalem dekat Pintu Gerbang Domba" },
  { nomor: 527, soal: "Berapa serambi kolam Bethesda?", jawaban: "Lima serambi" },
  { nomor: 528, soal: "Sudah berapa lama orang sakit di Bethesda menderita?", jawaban: "Tiga puluh delapan tahun" },
  { nomor: 529, soal: "Apa nama hari raya orang Yahudi?", jawaban: "Hari Raya Pondok Daun" },
  { nomor: 530, soal: "Siapakah Imam Kepala yang membela Yesus?", jawaban: "Nikodemus" },
  { nomor: 531, soal: "Siapakah bapa segala dusta?", jawaban: "Iblis" },
  { nomor: 532, soal: "Dimana orang buta disuruh membasuh diri?", jawaban: "Kolam Siloam" },
  { nomor: 533, soal: "Apa arti Siloam?", jawaban: "Yang diutus" },
  { nomor: 534, soal: "Apa arti Yohanes 11:25tentang orang percaya?", jawaban: "Ia akan hidup walaupun sudah mati" },
  { nomor: 535, soal: "Kepada siapa Yesus pertama kali dihadapkan setelah ditangkap?", jawaban: "Hanas" },
  { nomor: 536, soal: "Setelah Hanas Yesus dibawa kepada siapa?", jawaban: "Kayafas" },
  { nomor: 537, soal: "Setelah Kayafas Yesus dibawa kemana?", jawaban: "Kepada Pilatus" },
  { nomor: 538, soal: "Apa arti Litostrotos?", jawaban: "Tempat duduk pengadilan" },
  { nomor: 539, soal: "Apa yang dibawa Nikodemus kepada Yesus?", jawaban: "Campuran mur dan gaharu sekitar lima puluh kati" },
  { nomor: 540, soal: "Siapa dua murid yang datang ke kubur lalu pulang?", jawaban: "Petrus dan Yohanes" },
  { nomor: 541, soal: "Apa perkataan Yesus saat mengembusi murid-murid?", jawaban: "Terimalah Roh Kudus" },
  { nomor: 542, soal: "Siapakah murid yang tidak percaya sebelum melihat bekas paku?", jawaban: "Tomas Didimus" },
  { nomor: 543, soal: "Siapa murid di Danau Tiberias saat Yesus menampakkan diri?", jawaban: "Petrus,Tomas,Natanael," },
  { nomor: 544, soal: "Apa arti Zakharia?", jawaban: "Tuhan telah mengingat" },
  { nomor: 545, soal: "Siapakah ayah Zakharia nabi?", jawaban: "Berekhya bin Ido" },
  { nomor: 546, soal: "Kapan firman Tuhan datang kepada Zakharia pertama kali?", jawaban: "Bulan 8tahun kedua Raja Darius 547.Kapan penglihatan-penglihatan Zakharia diterima?Hari 24bulan 11tahun kedua Darius" },
  { nomor: 548, soal: "Pasal 1–8Zakharia berisi tentang apa?", jawaban: "Penglihatan-penglihatan" },
  { nomor: 549, soal: "Sebutkan delapan penglihatan Zakharia?", jawaban: "Penunggang kuda,empat tanduk,tali ukur,Imam Yosua,kandil emas,gulungan kitab,perempuan dalam gantang,empat kereta" },
  { nomor: 550, soal: "Kapan firman Tuhan tentang puasa datang?", jawaban: "Tahun keempat Raja Darius" },
  { nomor: 551, soal: "Siapakah bupati Yehuda zaman Darius?", jawaban: "Zerubabel" },
  { nomor: 552, soal: "Siapakah Imam Besar zaman Darius?", jawaban: "Yosua bin Yozadak" },
  { nomor: 553, soal: "Siapa yang pulang lebih dahulu dari Babel?", jawaban: "Heldai,Tobia,dan Yedaya" },
  { nomor: 554, soal: "Siapa utusan penduduk Betel?", jawaban: "Sarezer dan Regem-Melekh" },
  { nomor: 555, soal: "Kuda apa menarik empat kereta Zakharia?", jawaban: "Merah,hitam,putih,dan berbelang" },
  { nomor: 556, soal: "Apa dua tongkat gembala?", jawaban: "Tongkat kemurahan dan tongkat ikatan" },
  { nomor: 557, soal: "Berapa upah gembala?", jawaban: "Tiga puluh uang perak" },
  { nomor: 558, soal: "Apa simbol Yerusalem menjadi pasu?", jawaban: "Kekuasaan dan kedaulatan" },
  { nomor: 559, soal: "Kaum Yehuda menjadi seperti apa?", jawaban: "Anglo berapi dan suluh berapi" },
  { nomor: 560, soal: "Ratapan Yerusalem sebanding dengan apa?", jawaban: "Ratapan Hadad-Rimon" },
  { nomor: 561, soal: "Pada zaman siapa terjadi gempa besar?", jawaban: "Raja Uzia" },
  { nomor: 562, soal: "Tulah apa bagi bangsa yang menyerang Yerusalem?", jawaban: "Daging,mata,dan lidah menjadi busuk 563.Tulah itu menimpa apa saja?Kuda,bagal,unta,keledai,dan semua hewan" },
  { nomor: 564, soal: "Apa akibat tidak datang menyembah Tuhan?", jawaban: "Tidak turun hujan" },
  { nomor: 565, soal: "Berapa lama Yerusalem rusak?", jawaban: "Tujuh puluh tahun" },
  { nomor: 566, soal: "Mengapa Tuhan menurunkan air bah?", jawaban: "Karena kejahatan manusia besar" },
  { nomor: 567, soal: "Kemana Abram pergi sebelum berpisah dengan Lot?", jawaban: "Tanah Negeb" },
  { nomor: 568, soal: "Siapakah ayah Musa?", jawaban: "Amram" },
  { nomor: 569, soal: "Apa yang dimusnahkan oleh air bah?", jawaban: "Manusia dan semua makhluk hidup" },
  { nomor: 570, soal: "Dimana Abram tinggal sebelum Haran?", jawaban: "Ur-Kasdim" },
  { nomor: 571, soal: "Dimana Abraham mempersembahkan Ishak?", jawaban: "Gunung Moria" },
  { nomor: 572, soal: "Mengapa Abram dan Lot berpisah?", jawaban: "Supaya tidak terjadi perkelahian" },
  { nomor: 573, soal: "Apa alas kepala Yakub di Betel?", jawaban: "Batu" },
  { nomor: 574, soal: "Mengapa istri tuan Mesir menyukai Yusuf?", jawaban: "Karena Yusuf elok parasnya" },
  { nomor: 575, soal: "Siapakah ibu Musa?", jawaban: "Yokhebed" },
  { nomor: 576, soal: "Siapakah keluarga Abraham dekat Sodom?", jawaban: "Lot" },
  { nomor: 577, soal: "Berapa bujang ikut Abraham ke Moria?", jawaban: "Dua orang" },
  { nomor: 578, soal: "Apa yang Yakub lihat di Betel?", jawaban: "Tangga sampai ke sorga" },
  { nomor: 579, soal: "Berapa umur Yusuf menggembalakan domba?", jawaban: "Tujuh belas tahun" },
  { nomor: 580, soal: "Bangsa apa memperbudak Israel saat Musa lahir?", jawaban: "Mesir" },
  { nomor: 581, soal: "Siapa berkata darah adikmu berteriak?", jawaban: "Tuhan" },
  { nomor: 582, soal: "Kemana Yakub disuruh pergi?", jawaban: "Padang Aram ke Haran" },
  { nomor: 583, soal: "Dimana juru roti dan minuman dipenjara?", jawaban: "Rumah kepala pengawal" },
  { nomor: 584, soal: "Apa yang Yusuf lakukan saat memperkenalkan diri?", jawaban: "Menangis keras" },
  { nomor: 585, soal: "Siapa mengusulkan menjual Yusuf?", jawaban: "Yehuda" },
  { nomor: 586, soal: "Siapa berkata ini rumah Allah?", jawaban: "Yakub" },
  { nomor: 587, soal: "Apa arti nama Kain?", jawaban: "Saya menghasilkan" },
  { nomor: 588, soal: "Berapa hari Abraham ke Moria?", jawaban: "Tiga hari" },
  { nomor: 589, soal: "Apa perbedaan Esau dan Yakub?", jawaban: "Esau berbulu,Yakub licin" },
  { nomor: 590, soal: "Apa nama lama Betel?", jawaban: "Lus" },
  { nomor: 591, soal: "Nama baru Yakub dari Tuhan?", jawaban: "Israel" },
  { nomor: 592, soal: "Siapa kakak perempuan Musa?", jawaban: "Miryam" },
  { nomor: 593, soal: "Apa persembahan Kain?", jawaban: "Hasil tanah" },
  { nomor: 594, soal: "Dimana Terah menetap?", jawaban: "Haran" },
  { nomor: 595, soal: "Mengapa Lot memilih Lembah Yordan?", jawaban: "Banyak air" },
  { nomor: 596, soal: "Siapa menerima berkat Ishak?", jawaban: "Yakub" },
  { nomor: 597, soal: "Berapa bagian nazar Yakub?", jawaban: "Sepersepuluh" },
  { nomor: 598, soal: "Siapa ibu saudara Yusuf dari gundik?", jawaban: "Bilha dan Zilpa" },
  { nomor: 599, soal: "Ayah dan ibu Musa dari suku apa?", jawaban: "Lewi 600.Apa persembahan Habel?Anak sulung kambing domba 601.Berapa tingkat bahtera Nuh?Tiga tingkat 602.Berapa umur Terah saat meninggal?Dua ratus lima puluh tahun 603.Apa perlengkapan Abraham ke Moria?Kayu,api,dan pisau 604.Dimana Abram mendirikan mezbah?Mamre dekat Hebron 605.Bagaimana keadaan mata Ishak?Kabur 606.Apa kata Yakub setelah mimpi?Tuhan ada di tempat ini 607.Mengapa Yusuf dibenci saudara-saudaranya?Karena jubah indah dan dikasihi ayahnya 608.Berapa lama Musa disembunyikan?Tiga bulan 609.Siapa berkata mendapat anak dengan pertolongan Tuhan?Hawa 610.Siapa mengusulkan Yusuf ke sumur?Ruben 611.Mengapa Ishak salah mengenali Yakub?Karena tangan Yakub berbulu 612.Mengapa juru roti dan minuman bersusah hati?Karena mimpi tidak ada penafsir 613.Mengapa Yusuf dikasihi tuannya?Karena Tuhan menyertainya 614.Siapakah yang mengatakan \"Bangunlah,bawalah isterimu dan kedua anakmu yang ada di sini,supaya engkau jangan mati lenyap karena kedurjanaan kota ini\"?Dua malaikat Tuhan" },
  { nomor: 615, soal: "Apa arti Habel?", jawaban: "Kekosongan 616.Apa yang terjadi saat Kain mempersembahkan korban persembahannya?Korban persembahannya tidak diindahkan Tuhan" },
  { nomor: 617, soal: "Dengan apa bahtera Nuh harus ditutup dari luar dan dari dalam?", jawaban: "Pakal" },
  { nomor: 621, soal: "Apa yang diminta Ishak kepada Esau sebelum memberkati dia?", jawaban: "Berburu binatang dan mengolah makanan yang enak" },
  { nomor: 622, soal: "Seperti apa keturunan Yakub diumpamakan Tuhan dalam mimpi?", jawaban: "Seperti debu tanah banyaknya" },
  { nomor: 623, soal: "Mengapa Yakub lebih mengasihi Yusuf?", jawaban: "Karena Yusuf lahir pada masa tuanya" },
  { nomor: 626, soal: "Mengapa Nuh dipilih Tuhan membangun bahtera?", jawaban: "Karena Nuh benar,tidak bercela,dan hidup bergaul dengan Allah" },
  { nomor: 627, soal: "Apa janji Tuhan kepada Abram saat keluar dari Haran?", jawaban: "Menjadi bangsa besar,diberkati,dan menjadi berkat" },
  { nomor: 628, soal: "Bagaimana keadaan orang Sodom menurut Alkitab?", jawaban: "Sangat jahat dan berdosa terhadap Tuhan" },
  { nomor: 629, soal: "Berapa kali malaikat Tuhan memanggil nama Abraham di Gunung Moria?", jawaban: "Dua kali" },
  { nomor: 630, soal: "Tugu batu yang didirikan Yakub akan menjadi apa?", jawaban: "Rumah Allah" },
  { nomor: 632, soal: "Berapa umur Abram saat berangkat dari Haran?", jawaban: "Tujuh puluh lima tahun" },
  { nomor: 634, soal: "Binatang apa pengganti Ishak sebagai korban?", jawaban: "Domba jantan" },
  { nomor: 638, soal: "Apa mimpi juru minuman Firaun?", jawaban: "Pohon anggur dengan tiga carang dan piala Firaun" },
  { nomor: 639, soal: "Mengapa Ruben mengusulkan Yusuf dimasukkan ke sumur?", jawaban: "Supaya dapat menyelamatkannya kemudian" },
  { nomor: 640, soal: "Siapakah yang berkata \"Aku akan menghapuskan manusia dari muka bumi\"?", jawaban: "Tuhan" },
  { nomor: 641, soal: "Apa arti nama Abraham?", jawaban: "Bapak orang beriman" },
  { nomor: 642, soal: "Bagaimana Kain membunuh Habel?", jawaban: "Dengan memukulnya" },
  { nomor: 643, soal: "Berapa pasang binatang masuk ke bahtera?", jawaban: "Satu pasang jantan dan betina" },
  { nomor: 644, soal: "Siapakah ayah Lot?", jawaban: "Haran" },
  { nomor: 645, soal: "Kapan malaikat tiba di Sodom menemui Lot?", jawaban: "Pada waktu petang" },
  { nomor: 646, soal: "Apa nama tempat persembahan Ishak?", jawaban: "Tuhan Menyediakan" },
  { nomor: 647, soal: "Pakaian siapa dipakai Yakub untuk menipu Ishak?", jawaban: "Pakaian Esau yang indah" },
  { nomor: 648, soal: "Apa isi nazar Yakub di Betel?", jawaban: "Tuhan akan menjadi Allahku" },
  { nomor: 649, soal: "Apa mimpi kedua Yusuf?", jawaban: "Matahari,bulan,dan sebelas bintang sujud kepadanya" },
  { nomor: 651, soal: "Dimana Kain menetap setelah membunuh Habel?", jawaban: "Tanah Nod di sebelah timur Eden" },
  { nomor: 652, soal: "Siapa yang dibawa Abram keluar dari Haran?", jawaban: "Sarai,Lot,harta benda,dan budak-budaknya" },
  { nomor: 653, soal: "Apa yang terjadi pada istri Lot yang menoleh ke belakang?", jawaban: "Menjadi tiang garam" },
  { nomor: 655, soal: "Dimana keluarga Yakub tinggal di Mesir?", jawaban: "Tanah Gosyen" },
  { nomor: 656, soal: "Apa sebutan Yakub untuk tempat Betel?", jawaban: "Pintu gerbang sorga" },
  { nomor: 657, soal: "Kemana Yusuf dilemparkan oleh saudara-saudaranya?", jawaban: "Ke dalam sumur kosong" },
  { nomor: 659, soal: "Berapa kali lipat pembalasan bagi pembunuh Kain?", jawaban: "Tujuh kali lipat" },
  { nomor: 660, soal: "Berapa kali Yakub menipu Esau?", jawaban: "Dua kali" },
  { nomor: 661, soal: "Berapa malaikat yang menolong Lot keluar dari Sodom?", jawaban: "Dua malaikat" },
  { nomor: 662, soal: "Keturunan Abraham diumpamakan seperti apa?", jawaban: "Bintang di langit dan pasir di laut" },
  { nomor: 664, soal: "Kepada siapa Yusuf dijual?", jawaban: "Kafilah orang Ismael" },
  { nomor: 665, soal: "Sungai apa di tepi tempat Firaun bermimpi?", jawaban: "Sungai Nil" },
  { nomor: 666, soal: "Apa pemberian khusus Yusuf kepada Benyamin?", jawaban: "Tiga ratus uang perak dan lima potong pesalin" },
  { nomor: 667, soal: "Berapa lama air bah menutupi bumi?", jawaban: "Seratus lima puluh hari" },
  { nomor: 668, soal: "Siapa yang berkata Allah menyediakan korban?", jawaban: "Abraham" },
  { nomor: 669, soal: "Apa arti mimpi juru minuman menurut Yusuf?", jawaban: "Tiga hari dan dipulihkan jabatannya" },
  { nomor: 670, soal: "Kemana Abram berangkat dari pegunungan Ai?", jawaban: "Tanah Negeb" },
  { nomor: 671, soal: "Apa yang Tuhan lakukan agar Kain tidak dibunuh?", jawaban: "Memberi tanda pada Kain" },
  { nomor: 672, soal: "Berapa lama setelah juru minuman bebas Firaun bermimpi?", jawaban: "Dua tahun" },
  { nomor: 673, soal: "Berapa jumlah orang benar pertama yang Abraham ajukan?", jawaban: "Lima puluh orang" },
  { nomor: 674, soal: "Apa yang dilakukan malaikat kepada orang Sodom?", jawaban: "Membutakan mata mereka" },
  { nomor: 676, soal: "Apa yang dilakukan saudara Yusuf setelah melemparkan dia ke sumur?", jawaban: "Duduk makan" },
  { nomor: 677, soal: "Kemana saudagar membawa Yusuf?", jawaban: "Ke Mesir" },
  { nomor: 678, soal: "Apa pelajaran dari kisah Kain dan Habel?", jawaban: "Tuhan itu pengampun" },
  { nomor: 679, soal: "Apa reaksi Esau saat berkatnya dirampas?", jawaban: "Meraung-raung dengan sangat keras" },
  { nomor: 681, soal: "Apa yang dilakukan saudara Yusuf pada jubahnya?", jawaban: "Dirobek dan dilumuri darah kambing" },
  { nomor: 682, soal: "Berapa harga Yusuf dijual?", jawaban: "Dua puluh syikal perak" },
  { nomor: 683, soal: "Apa hukuman Tuhan atas Kain?", jawaban: "Menjadi pengembara dan tanah tidak menghasilkan" },
  { nomor: 684, soal: "Berapa kali Abraham memohon bagi Sodom?", jawaban: "Lima kali" },
  { nomor: 685, soal: "Kapan Lot meninggalkan Sodom?", jawaban: "Saat fajar menyingsing" },
  { nomor: 686, soal: "Barang apa dibawa kafilah pembeli Yusuf?", jawaban: "Damar,balsam,dan damar ladan" },
  { nomor: 687, soal: "Siapa orang Mesir yang membeli Yusuf?", jawaban: "Potifar" },
  { nomor: 688, soal: "Berapa bagian hasil Mesir dipungut Firaun?", jawaban: "Seperlima bagian" },
  { nomor: 689, soal: "Apa pelajaran dari Yakub di Betel?", jawaban: "Tuhan itu Pelindung" },
  { nomor: 690, soal: "Berapa orang yang selamat dari Sodom?", jawaban: "Tiga orang" },
  { nomor: 691, soal: "Ke kota mana Lot diperintahkan pergi?", jawaban: "Zoar" },
  { nomor: 692, soal: "Bagian tubuh mana ditutupi Yakub dengan kulit kambing?", jawaban: "Tangan dan leher" },
  { nomor: 693, soal: "Apa jabatan Potifar?", jawaban: "Kepala pengawal raja" },
  { nomor: 694, soal: "Berkat apa yang diterima Yakub dari Ishak?", jawaban: "Embun langit,tanah subur,bangsa-bangsa takluk,dan berkat Allah" },
  { nomor: 695, soal: "Berapa tahun kelaparan tersisa saat Yusuf memperkenalkan diri?", jawaban: "Lima tahun" },
  { nomor: 697, soal: "Apa bekal Yusuf untuk ayahnya ke Mesir?", jawaban: "Keledai berisi hasil terbaik Mesir dan makanan" },
  { nomor: 698, soal: "Apa mimpi kedua Firaun?", jawaban: "Tujuh bulir gandum gemuk dimakan tujuh bulir kurus" },
  { nomor: 699, soal: "Apa arti nama Israel?", jawaban: "Allah bergumul" },
  { nomor: 700, soal: "Apa ucapan pertama Yusuf setelah mendengar mimpi Firaun?", jawaban: "Allah memberitahukan apa yang akan dilakukan-Nya" },
  { nomor: 701, soal: "Siapa anak tertua Kain?", jawaban: "Henokh" },
  { nomor: 702, soal: "Anak Nuh mana disebut bapa Kanaan?", jawaban: "Ham" },
  { nomor: 703, soal: "Siapa menopang tangan Musa melawan Amalek?", jawaban: "Harun dan Hur" },
  { nomor: 704, soal: "Siapa pelihat yang diminta Balak?", jawaban: "Bileam bin Beor" },
  { nomor: 705, soal: "Gedung Hutan Libanon adalah apa?", jawaban: "Istana Salomo" },
  { nomor: 706, soal: "Ayat \"oleh bilur-bilurnya kita sembuh\"terdapat di mana?", jawaban: "Yesaya 53:5" },
  { nomor: 707, soal: "Sungai apa terbelah saat Israel menyeberang?", jawaban: "Sungai Yordan" },
  { nomor: 708, soal: "Nabi yang berjalan telanjang tiga tahun?", jawaban: "Yesaya" },
  { nomor: 709, soal: "Rehabeam adalah anak siapa?", jawaban: "Raja Salomo" },
  { nomor: 710, soal: "Siapa orang Horon yang mengolok Nehemia?", jawaban: "Sanbalat" },
  { nomor: 711, soal: "Siapa nabi yang botak?", jawaban: "Elisa" },
  { nomor: 712, soal: "Apa nama Babel Daniel,Hananya,Misael,dan Azarya?", jawaban: "Beltsazar,Sadrakh,Mesakh,Abednego" },
  { nomor: 713, soal: "Alat tukar zaman Rut?", jawaban: "Kasut" },
  { nomor: 714, soal: "Apa yang dipakai Elisa menyehatkan air Yerikho?", jawaban: "Garam" },
  { nomor: 715, soal: "Siapakah nabi yang ditegur Tuhan agar tidak menyebut dirinya masih muda?", jawaban: "Nabi Yeremia" },
  { nomor: 717, soal: "Apa alasan Laban memberikan Lea lebih dahulu kepada Yakub?", jawaban: "Tidak biasa mengawinkan adik lebih dahulu daripada kakaknya" },
  { nomor: 718, soal: "Siapa yang pernah didatangi panglima bala tentara Tuhan?", jawaban: "Yosua" },
  { nomor: 719, soal: "Dimanakah tertulis \"Besi menajamkan besi,orang menajamkan sesamanya\"?", jawaban: "Amsal 27:17" },
  { nomor: 720, soal: "Siapakah nabi yang mendapat penglihatan kemuliaan Tuhan di tepi Sungai Kebar?", jawaban: "Nabi" },
  { nomor: 721, soal: "Siapakah yang melakukan pertobatan massal dengan puasa manusia dan ternak?", jawaban: "Orang Niniwe 722.Apa arti kiasan Ohola dan Oholiba?Ohola adalah Samaria dan Oholiba adalah Yerusalem" },
  { nomor: 723, soal: "Di kitab apakah tertulis \"Cinta kuat seperti maut\"?", jawaban: "Kidung Agung 8:6" },
  { nomor: 724, soal: "Siapakah tiga sahabat Ayub?", jawaban: "Elifas,Bildad,dan Zofar" },
  { nomor: 725, soal: "Raja manakah yang bertubuh sangat gendut?", jawaban: "Eglon,raja Moab" },
  { nomor: 726, soal: "Anak Nuh yang mendapat kutuk karena melihat aurat ayahnya?", jawaban: "Ham" },
  { nomor: 727, soal: "Nama lain Salomo yang diberikan Tuhan?", jawaban: "Yedija" },
  { nomor: 728, soal: "Siapakah dua pengintai yang masuk tanah Kanaan?", jawaban: "Kaleb bin Yefune dan Yosua bin Nun" },
  { nomor: 729, soal: "Sayur apakah yang dimakan pada perayaan Paskah?", jawaban: "Sayur pahit" },
  { nomor: 730, soal: "Apa yang dimakan Yesus setelah kebangkitan-Nya?", jawaban: "Sepotong ikan goreng" },
  { nomor: 731, soal: "Berapa roti dan ikan untuk memberi makan 5000orang?", jawaban: "Lima roti dan dua ikan" },
  { nomor: 732, soal: "Di kota manakah Yesus menyembuhkan orang kerasukan di rumah ibadat?", jawaban: "Kapernaum" },
  { nomor: 733, soal: "Dimana tertulis bahwa akar segala kejahatan ialah cinta uang?", jawaban: "1Timotius 6:10" },
  { nomor: 734, soal: "Sungai apakah yang berubah menjadi darah?", jawaban: "Sungai Nil" },
  { nomor: 735, soal: "Apa arti Imanuel?", jawaban: "Allah menyertai kita" },
  { nomor: 736, soal: "Binatang apakah yang melambangkan keselamatan dan kesetiaan?", jawaban: "Burung merpati" },
  { nomor: 737, soal: "Burung apakah yang pertama dilepaskan Nuh?", jawaban: "Burung gagak" },
  { nomor: 738, soal: "Seperti pohon apakah orang benar dilambangkan?", jawaban: "Pohon kurma" },
  { nomor: 739, soal: "Batang tumbuhan apakah yang diunjukkan ke mulut Yesus menjelang kematian-Nya?", jawaban: "Hisop" },
  { nomor: 740, soal: "Daun apakah yang digunakan menyambut Yesus ke Yerusalem?", jawaban: "Daun palem" },
  { nomor: 741, soal: "Menurut Kidung Agung,apakah yang tidak dapat dihanyutkan sungai?", jawaban: "Cinta" },
  { nomor: 742, soal: "Gunung apakah di Yerusalem yang sering disebut dalam Alkitab?", jawaban: "Gunung Sion" },
  { nomor: 743, soal: "Dimanakah Yesus menyampaikan khotbah terakhir-Nya?", jawaban: "Bukit Zaitun" },
];